(function () {
    const source = { kind: 'original', note: '스마트 스터디 자체 제작' };
    const q = (id, type, prompt, choices, answerIndex, explanation, evidence) => {
        const questionNumber = Number(id.match(/q(\d+)$/)?.[1] || 1);
        const shift = (questionNumber - 1) % choices.length;
        const rotatedChoices = choices.slice(shift).concat(choices.slice(0, shift));
        return { id, type, prompt, choices: rotatedChoices, answerIndex: (answerIndex - shift + choices.length) % choices.length, explanation, evidence };
    };
    const lessonIndexByUnit = { e3: 0, e4: 0, e5: 1, e6: 0 };
    const p = (id, title, topic, band, sentences, translations, vocabulary, grammarTags, grammarNotes, questions) => ({
        id, title, topic, band, sentences, translations, vocabulary, grammarTags,
        grammarRefs: grammarTags.slice(0, 1).map(unitId => ({ stageId: 'elementary', unitId, lessonIndex: lessonIndexByUnit[unitId] ?? 0 })),
        grammarNotes, questions, source: { ...source }
    });

    window.EnglishReadingData = {
        version: '20260929-er-expanded',
        levels: [
            { id: 'grade6', title: '초6 · 기초 독해', available: true },
            { id: 'middle1', title: '중1 · 기본 독해', available: false },
            { id: 'middle2', title: '중2 · 확장 독해', available: false },
            { id: 'middle3', title: '중3 · 심화 독해', available: false }
        ],
        units: [
            {
                id: 'er1', title: '1. 달을 바라보는 밤', goal: '관찰한 사실과 생각을 구분하며 달에 관한 글을 읽습니다.',
                passages: [
                    p('er1-p0', 'A Moon Journal', '달 관찰 일기', 0,
                        ['Mina looks at the moon after dinner.', 'On Monday, it is a thin curve.', 'Three nights later, the bright part is wider.', 'Mina draws each shape in her notebook.', 'She learns that the moon seems to change over time.'],
                        ['미나는 저녁 식사 후 달을 바라봅니다.', '월요일에는 달이 가느다란 곡선 모양입니다.', '사흘 뒤에는 밝은 부분이 더 넓습니다.', '미나는 공책에 각각의 모양을 그립니다.', '그녀는 달이 시간이 지나며 변하는 것처럼 보인다는 것을 배웁니다.'],
                        [{ word: 'moon', meaning: '달' }, { word: 'shape', meaning: '모양' }, { word: 'change', meaning: '변하다' }, { word: 'curve', meaning: '곡선' }, { word: 'wider', meaning: '더 넓은' }, { word: 'seem', meaning: '~처럼 보이다' }],
                        ['e3', 'e6'], [{ title: '3인칭 단수', text: '주어가 Mina나 she일 때 현재형 동사에 보통 -s를 붙입니다.' }],
                        [q('er1-p0-q1','fact','What does Mina do after dinner?',['She looks at the moon.','She calls her friend.','She reads a comic.','She cooks a meal.'],0,'첫 문장에 미나가 저녁 식사 후 달을 본다고 나옵니다.',[0]),q('er1-p0-q2','main','What is the passage mainly about?',['A girl records changes in the moon.','A family plans a dinner.','A teacher draws a notebook.','A cloudy week begins.'],0,'미나가 달의 모양을 여러 날 관찰하고 기록하는 내용입니다.',[0,2,3,4]),q('er1-p0-q3','vocabulary','What does “wider” mean in sentence 3?',['more broad','less bright','more distant','perfectly round'],0,'wider는 폭이 더 넓다는 뜻입니다.',[2]),q('er1-p0-q4','reference','Who does “She” in sentence 5 refer to?',['Mina','the moon','Monday','a notebook'],0,'앞 문장들의 행동 주체인 Mina를 가리킵니다.',[3,4]),q('er1-p0-q5','evidence','Which sentence best shows that Mina keeps a record?',['Sentence 1','Sentence 2','Sentence 3','Sentence 4'],3,'공책에 모양을 그린다는 네 번째 문장이 기록 행동을 직접 보여 줍니다.',[3])]),
                    p('er1-p1', 'Why the Moon Shines', '달빛의 원리', 1,
                        ['The moon does not make its own light.', 'Sunlight reaches the moon and bounces off its surface.', 'Some of that reflected light travels to our eyes.', 'The moon looks bright even when the sky around it is dark.', 'For this reason, the light we call moonlight comes from the sun.'],
                        ['달은 스스로 빛을 만들지 않습니다.', '햇빛이 달에 닿아 표면에서 반사됩니다.', '그 반사된 빛의 일부가 우리 눈까지 옵니다.', '주변 하늘이 어두울 때도 달은 밝아 보입니다.', '이 때문에 우리가 달빛이라고 부르는 빛은 태양에서 옵니다.'],
                        [{ word: 'sunlight', meaning: '햇빛' }, { word: 'bright', meaning: '밝은' }, { word: 'reason', meaning: '이유' }, { word: 'surface', meaning: '표면' }, { word: 'reflected', meaning: '반사된' }, { word: 'bounce', meaning: '튕기다, 반사되다' }],
                        ['e3', 'e6'], [{ title: 'even when', text: 'even when은 ‘~할 때조차’라는 뜻으로 예상과 다른 상황을 강조합니다.' }],
                        [q('er1-p1-q1','fact','What happens when sunlight reaches the moon?',['It bounces off the surface.','It turns into water.','It stops moving forever.','It comes from the moon itself.'],0,'두 번째 문장이 햇빛이 달 표면에서 반사된다고 설명합니다.',[1]),q('er1-p1-q2','main','What does the passage explain?',['How we can see moonlight','Why the sun moves at night','How eyes make their own light','Why the moon is made of glass'],0,'달빛이 햇빛의 반사로 우리 눈에 도달하는 과정을 설명합니다.',[0,1,2]),q('er1-p1-q3','vocabulary','What is “reflected light”?',['light sent back from a surface','light made inside an eye','light hidden by a cloud','light stored in a lamp'],0,'reflect는 표면에 닿은 빛을 되돌려 보내는 것입니다.',[1,2]),q('er1-p1-q4','reference','What does “Some of that reflected light” refer to?',['sunlight bouncing off the moon','light made by the moon','stars behind the moon','lamps on Earth'],0,'앞 문장의 달 표면에서 튕겨 나온 햇빛을 가리킵니다.',[1,2]),q('er1-p1-q5','evidence','Which sentences give the cause-and-effect steps for seeing the moon?',['Sentences 1 and 5','Sentences 2 and 3','Sentences 3 and 4','Sentences 4 and 5'],1,'2문장은 반사를, 3문장은 그 빛이 눈에 오는 결과를 제시합니다.',[1,2])]),
                    p('er1-p2', 'A Calendar in the Sky', '달의 위상과 생활', 2,
                        ['Long before printed calendars, people watched the moon to measure time.', 'A full cycle of changing shapes takes about twenty-nine and a half days.', 'People could count these cycles to follow the passing months.', 'They also watched other signs in nature when they planned seasonal work.', 'The moon was not a perfect clock, but its repeated pattern was a useful guide.'],
                        ['인쇄된 달력이 생기기 훨씬 전, 사람들은 시간을 재기 위해 달을 관찰했습니다.', '모양이 변하는 한 주기는 약 29일 반이 걸립니다.', '사람들은 지나가는 달을 헤아리기 위해 이러한 주기를 셀 수 있었습니다.', '계절의 일을 계획할 때는 자연의 다른 신호들도 살폈습니다.', '달은 완벽한 시계가 아니었지만 반복되는 무늬는 유용한 길잡이였습니다.'],
                        [{ word: 'nature', meaning: '자연' }, { word: 'clock', meaning: '시계' }, { word: 'useful', meaning: '유용한' }, { word: 'cycle', meaning: '주기' }, { word: 'seasonal', meaning: '계절의' }, { word: 'guide', meaning: '길잡이' }],
                        ['e4', 'e6'], [{ title: '목적을 나타내는 to', text: 'to measure는 ‘시간을 재기 위해’라는 행동의 목적을 나타냅니다.' }],
                        [q('er1-p2-q1','fact','About how long is one cycle of moon shapes?',['one week','two weeks','twenty-nine and a half days','one year'],2,'두 번째 문장에 약 29일 반이라고 제시되어 있습니다.',[1]),q('er1-p2-q2','main','What is the central idea?',['Moon patterns helped people keep track of time.','The moon was a perfectly exact clock.','Printed calendars were made on the moon.','People ignored every other sign in nature.'],0,'반복되는 달의 변화를 시간의 길잡이로 활용했다는 글입니다.',[0,2,4]),q('er1-p2-q3','vocabulary','What does “guide” most nearly mean?',['a helpful sign','a loud warning','a written law','a heavy tool'],0,'문맥상 시간을 헤아리는 데 도움을 주는 길잡이입니다.',[4]),q('er1-p2-q4','reference','What does “these cycles” refer to?',['the moon’s changing shapes','printed calendars','seasonal jobs','other signs in nature'],0,'앞 문장의 달 모양이 변하는 주기를 가리킵니다.',[1,2]),q('er1-p2-q5','evidence','Which sentence shows that people did not rely on the moon alone?',['Sentence 1','Sentence 2','Sentence 4','Sentence 5'],2,'네 번째 문장이 자연의 다른 신호도 살폈다고 밝힙니다.',[3])])
                ]
            },
            {
                id: 'er2', title: '2. 가족이 함께하는 방법', goal: '인물의 행동과 마음을 근거로 가족 관계를 이해합니다.',
                passages: [
                    p('er2-p0','The Saturday List','가족의 집안일',0,
                        ['Every Saturday, Jun’s family makes a short job list.', 'Jun waters the plants, and his sister sorts the laundry.', 'Their father cooks lunch while their mother fixes small things around the house.', 'They finish faster because everyone has a clear task.', 'Afterward, they play a board game together.'],
                        ['매주 토요일, 준이네 가족은 짧은 할 일 목록을 만듭니다.', '준은 식물에 물을 주고 여동생은 빨래를 분류합니다.', '아버지는 점심을 만들고 그동안 어머니는 집 안의 작은 것들을 고칩니다.', '모두에게 분명한 일이 있어서 더 빨리 끝냅니다.', '그 뒤 그들은 함께 보드게임을 합니다.'],
                        [{ word:'family',meaning:'가족'},{word:'job',meaning:'일, 할 일'},{word:'together',meaning:'함께'},{word:'sort',meaning:'분류하다'},{word:'laundry',meaning:'빨래'},{word:'task',meaning:'맡은 일'}],
                        ['e3','e6'],[{title:'while과 because',text:'while은 동시에 일어나는 일을, because는 이유를 연결합니다.'}],
                        [q('er2-p0-q1','fact','What does Jun do?',['He waters the plants.','He cooks lunch.','He fixes a chair.','He sorts the laundry.'],0,'두 번째 문장에 준의 일이 나옵니다.',[1]),q('er2-p0-q2','main','What is the passage mainly about?',['A family shares work and fun.','Jun grows food for lunch.','A family buys a new house.','Two children dislike Saturdays.'],0,'가족이 집안일을 나누고 함께 놀이하는 내용입니다.',[0,1,2,4]),q('er2-p0-q3','vocabulary','What does “task” mean here?',['a job to do','a place to rest','a kind of plant','a family meal'],0,'문맥상 각자 맡아 해야 하는 일을 뜻합니다.',[3]),q('er2-p0-q4','reference','Who are “They” in sentence 4?',['Jun’s family','Jun and one plant','the parents only','the board games'],0,'앞에서 여러 일을 하는 준의 가족 전체를 가리킵니다.',[0,3]),q('er2-p0-q5','evidence','Which sentence explains why the work ends quickly?',['Sentence 1','Sentence 2','Sentence 4','Sentence 5'],2,'네 번째 문장이 분명한 역할 분담을 이유로 직접 제시합니다.',[3])]),
                    p('er2-p1','Grandma’s Voice Note','세대 간 소통',1,
                        ['Sora’s grandmother lives in another city, so they cannot meet every week.', 'On Sunday evening, Sora records a voice message about school and her new puppy.', 'Grandma replies with a story from her own childhood.', 'Although the messages are short, both of them listen more than once.', 'These messages help them share their lives even when they are far apart.'],
                        ['소라의 할머니는 다른 도시에 살아서 매주 만날 수 없습니다.', '일요일 저녁, 소라는 학교와 새 강아지에 관한 음성 메시지를 녹음합니다.', '할머니는 자신의 어린 시절 이야기로 답합니다.', '메시지는 짧지만 두 사람 모두 한 번 넘게 듣습니다.', '이 메시지들은 두 사람이 멀리 떨어져 있어도 서로의 생활을 나누도록 도와줍니다.'],
                        [{word:'record',meaning:'녹음하다'},{word:'reply',meaning:'답하다'},{word:'listen',meaning:'듣다'},{word:'childhood',meaning:'어린 시절'},{word:'message',meaning:'메시지'},{word:'apart',meaning:'떨어져'}],
                        ['e5','e6'],[{title:'Although',text:'although는 ‘비록 ~이지만’의 뜻으로 서로 대조되는 내용을 잇습니다.'}],
                        [q('er2-p1-q1','fact','What does Grandma send back?',['a childhood story','a new puppy','a school book','a train ticket'],0,'세 번째 문장에 할머니가 어린 시절 이야기로 답한다고 나옵니다.',[2]),q('er2-p1-q2','main','What is the main idea?',['Voice messages help two generations stay connected.','Sora wants to move to another city.','Grandma teaches Sora how to train a puppy.','Long messages are always better than short ones.'],0,'짧은 음성 메시지로 서로의 생활을 나누며 관계를 이어 갑니다.',[1,2,3,4]),q('er2-p1-q3','vocabulary','What does “far apart” mean in sentence 5?',['a long distance from each other','in the same room','at the same time','very often'],0,'서로 멀리 떨어져 있다는 뜻입니다.',[4]),q('er2-p1-q4','reference','Who does “both of them” refer to?',['Sora and Grandma','Sora and the puppy','Grandma and a teacher','two childhood friends'],0,'메시지를 주고받는 소라와 할머니 두 사람입니다.',[0,3]),q('er2-p1-q5','evidence','Which sentence shows that the short messages matter to them?',['Sentence 1','Sentence 2','Sentence 3','Sentence 4'],3,'짧아도 여러 번 듣는다는 행동이 메시지를 소중히 여김을 보여 줍니다.',[3])]),
                    p('er2-p2','The Quiet Seat','가족의 배려와 경청',2,
                        ['Daniel likes to tell his family about his day at dinner.', 'One evening, he notices that his older brother, Leo, is very quiet.', 'Daniel stops talking and asks, “Do you want to tell me something?”', 'Leo is not ready at first, so Daniel waits and listens.', 'Later, Leo says that he made a mistake during a team project.'],
                        ['다니엘은 저녁 식사 때 가족에게 자신의 하루를 이야기하는 것을 좋아합니다.', '어느 저녁, 그는 형 리오가 매우 조용한 것을 알아챕니다.', '다니엘은 말을 멈추고 “나에게 무언가 말하고 싶어?”라고 묻습니다.', '리오는 처음에는 말할 준비가 되지 않아 다니엘은 기다리며 들어 줍니다.', '나중에 리오는 모둠 과제 중 실수했다고 말합니다.'],
                        [{word:'notice',meaning:'알아차리다'},{word:'quiet',meaning:'조용한'},{word:'team',meaning:'모둠, 팀'},{word:'wait',meaning:'기다리다'},{word:'listen',meaning:'듣다'},{word:'mistake',meaning:'실수'}],
                        ['e3','e6'],[{title:'직접 인용한 질문',text:'따옴표 안의 Do you want ...?는 상대에게 직접 묻는 의문문입니다.'}],
                        [q('er2-p2-q1','fact','What mistake does Leo mention?',['one in a team project','one in a soccer game','one while cooking dinner','one on a family trip'],0,'다섯 번째 문장이 모둠 과제에서의 실수라고 밝힙니다.',[4]),q('er2-p2-q2','main','What lesson does the passage suggest?',['We can help by waiting and listening.','Family meals should always be silent.','People must fix every mistake alone.','Brothers should never ask questions.'],0,'다니엘은 형이 준비될 때까지 기다리고 이야기를 들어 줍니다.',[2,3,4]),q('er2-p2-q3','vocabulary','What does “ready” mean in sentence 4?',['prepared to do something','angry about dinner','unable to hear','busy with a project'],0,'리오가 아직 말할 준비가 되지 않았다는 뜻입니다.',[3]),q('er2-p2-q4','reference','Who does “he” in sentence 2 refer to?',['Daniel','Leo','a teammate','their father'],0,'관찰하는 사람은 앞 문장의 주어 Daniel입니다.',[0,1]),q('er2-p2-q5','evidence','Which sentence shows that Daniel listens without rushing Leo?',['Sentence 1','Sentence 2','Sentence 3','Sentence 4'],3,'네 번째 문장이 다니엘이 기다리며 듣는다고 직접 말합니다.',[3])])
                ]
            },
            {
                id:'er3',title:'3. 음식이 식탁에 오기까지',goal:'음식의 과정과 선택을 순서와 원인·결과로 파악합니다.',
                passages:[
                    p('er3-p0','From Seed to Soup','채소의 성장과 요리',0,
                        ['Yuna plants three tomato seeds in spring.', 'She gives them water and puts the pot by a sunny window.', 'Weeks later, small yellow flowers appear.', 'The flowers become red tomatoes in summer.', 'Yuna uses the tomatoes in soup for her family.'],
                        ['유나는 봄에 토마토 씨앗 세 개를 심습니다.', '그녀는 씨앗에 물을 주고 화분을 햇볕 드는 창가에 둡니다.', '몇 주 뒤 작은 노란 꽃이 나타납니다.', '그 꽃들은 여름에 빨간 토마토가 됩니다.', '유나는 가족을 위한 수프에 그 토마토를 넣습니다.'],
                        [{word:'seed',meaning:'씨앗'},{word:'spring',meaning:'봄'},{word:'summer',meaning:'여름'},{word:'appear',meaning:'나타나다'},{word:'pot',meaning:'화분'},{word:'plant',meaning:'심다'}],
                        ['e3','e6'],[{title:'시간 표현',text:'in spring, weeks later, in summer가 사건의 순서를 알려 줍니다.'}],
                        [q('er3-p0-q1','fact','Where does Yuna put the pot?',['by a sunny window','under her bed','beside the soup bowl','outside the school'],0,'두 번째 문장에 햇볕 드는 창가라고 나옵니다.',[1]),q('er3-p0-q2','main','What does the passage describe?',['how tomatoes grow and become food','how to buy yellow flowers','why soup is eaten in spring','why windows need water'],0,'씨앗에서 토마토가 자라 수프가 되는 순서를 보여 줍니다.',[0,2,3,4]),q('er3-p0-q3','vocabulary','What does “appear” mean?',['come into sight','become smaller','move away','taste sweet'],0,'꽃이 새로 눈에 보이기 시작한다는 뜻입니다.',[2]),q('er3-p0-q4','reference','What does “them” in sentence 2 refer to?',['the tomato seeds','three windows','yellow flowers','Yuna’s family'],0,'직전 문장의 tomato seeds를 받습니다.',[0,1]),q('er3-p0-q5','evidence','Which sentence shows the final use of the tomatoes?',['Sentence 2','Sentence 3','Sentence 4','Sentence 5'],3,'다섯 번째 문장이 토마토를 수프에 쓴다고 밝힙니다.',[4])]),
                    p('er3-p1','The Lunchbox Test','균형 잡힌 식사',1,
                        ['Mr. Han asks his class to examine their lunchboxes by color.', 'Green spinach and orange carrots provide different nutrients.', 'Brown rice gives energy, while beans and eggs help build the body.', 'No single color can provide everything a growing child needs.', 'The class decides to add variety instead of searching for one perfect food.'],
                        ['한 선생님은 학생들에게 색깔을 기준으로 도시락을 살펴보게 합니다.', '초록 시금치와 주황 당근은 서로 다른 영양소를 제공합니다.', '현미는 에너지를 주고 콩과 달걀은 몸을 만드는 데 도움을 줍니다.', '어느 한 색깔도 성장하는 아이에게 필요한 모든 것을 제공할 수는 없습니다.', '반 학생들은 완벽한 음식 하나를 찾는 대신 다양성을 더하기로 합니다.'],
                        [{word:'provide',meaning:'제공하다'},{word:'energy',meaning:'에너지'},{word:'build',meaning:'만들다, 기르다'},{word:'examine',meaning:'살펴보다'},{word:'nutrient',meaning:'영양소'},{word:'variety',meaning:'다양성'}],
                        ['e5','e6'],[{title:'instead of',text:'instead of searching은 ‘찾는 대신’이라는 뜻입니다.'}],
                        [q('er3-p1-q1','fact','Which foods help build the body?',['beans and eggs','rice and carrots','spinach and rice','carrots and eggs only'],0,'세 번째 문장이 콩과 달걀의 역할을 설명합니다.',[2]),q('er3-p1-q2','main','What is the main message?',['Eating a variety of foods is useful.','Every lunchbox needs one perfect food.','Food color decides how it tastes.','Brown foods contain every nutrient.'],0,'한 음식만으로는 충분하지 않아 다양하게 먹자는 결론입니다.',[1,2,3,4]),q('er3-p1-q3','vocabulary','What does “provide” most nearly mean?',['give','hide','remove','measure'],0,'영양소나 에너지를 ‘제공하다’라는 뜻입니다.',[1,2]),q('er3-p1-q4','reference','What does “everything” in sentence 4 mean?',['all the nutrients and energy a child needs','all the colors in a lunchbox','every food in the classroom','every lesson Mr. Han teaches'],0,'앞 문장들의 영양소, 에너지, 성장에 필요한 것을 종합하여 가리킵니다.',[1,2,3]),q('er3-p1-q5','evidence','Which sentence directly rejects the idea of one perfect food?',['Sentence 1','Sentence 2','Sentence 4','Sentence 5'],2,'네 번째 문장은 어떤 한 색 음식도 모든 것을 주지 못한다고 직접 말합니다.',[3])]),
                    p('er3-p2','A Strawberry’s Long Trip','딸기의 포장과 이동',2,
                        ['Strawberries begin their trip on a farm.', 'Workers put the fruit into small boxes.', 'Soft paper between the berries helps stop bumps and bruises.', 'A truck carries the boxes to a store.', 'At the store, workers place the strawberries on a cool shelf.', 'Care at every step helps the fruit reach shoppers in good condition.'],
                        ['딸기는 농장에서 여정을 시작합니다.', '일하는 사람들은 딸기를 작은 상자에 담습니다.', '딸기 사이의 부드러운 종이는 부딪힘과 멍을 막는 데 도움을 줍니다.', '트럭은 상자들을 가게로 운반합니다.', '가게에서 일하는 사람들은 딸기를 시원한 선반에 놓습니다.', '모든 단계에서 조심히 다루면 딸기가 좋은 상태로 손님에게 도착하는 데 도움이 됩니다.'],
                        [{word:'fruit',meaning:'과일'},{word:'paper',meaning:'종이'},{word:'store',meaning:'가게'},{word:'bruise',meaning:'멍'},{word:'carry',meaning:'운반하다'},{word:'condition',meaning:'상태'}],
                        ['e3','e6'],[{title:'help + 동사원형',text:'helps stop과 helps the fruit reach에서 help 뒤에 동사원형이 옵니다.'}],
                        [q('er3-p2-q1','fact','Where do strawberries begin their trip?',['on a farm','in a school','at a bus stop','in a kitchen'],0,'첫 번째 문장이 농장에서 여정을 시작한다고 말합니다.',[0]),q('er3-p2-q2','main','What is the passage mainly about?',['how strawberries travel safely from a farm to a store','how shoppers grow berries at home','why trucks are kept on farms','why all fruit needs large boxes'],0,'딸기를 농장에서 포장하고 가게까지 옮기는 과정을 설명합니다.',[0,1,2,3,4,5]),q('er3-p2-q3','vocabulary','What does “bruises” mean in sentence 3?',['dark marks caused by bumps','small seeds inside fruit','drops of clean water','labels on a box'],0,'딸기가 부딪힐 때 생기는 멍 자국을 뜻합니다.',[2]),q('er3-p2-q4','reference','What does “the boxes” in sentence 4 refer to?',['the boxes holding strawberries','boxes for soft paper only','empty boxes at a school','boxes carried by shoppers'],0,'두 번째 문장에서 딸기를 담은 작은 상자들을 가리킵니다.',[1,3]),q('er3-p2-q5','evidence','Which sentence explains how workers protect the fruit from bumps?',['Sentence 1','Sentence 2','Sentence 3','Sentence 5'],2,'세 번째 문장이 딸기 사이의 부드러운 종이가 충격과 멍을 막는다고 설명합니다.',[2])])
                ]
            },
            {
                id:'er4',title:'4. 생활 속 작은 과학',goal:'일상 문제를 관찰·실험·근거로 해결하는 글을 읽습니다.',
                passages:[
                    p('er4-p0','The Cold Spoon','열의 이동',0,
                        ['Eli puts a metal spoon and a wooden spoon in warm soup.', 'After one minute, the metal handle feels hotter.', 'Heat moves through metal more easily than through wood.', 'The wooden handle stays cooler, so Eli can hold it comfortably.', 'The two spoons show why cooking tools often use wooden handles.'],
                        ['엘리는 따뜻한 수프에 금속 숟가락과 나무 숟가락을 넣습니다.', '1분 뒤 금속 손잡이가 더 뜨겁게 느껴집니다.', '열은 나무보다 금속을 더 쉽게 통과합니다.', '나무 손잡이는 더 차갑게 유지되어 엘리가 편안하게 잡을 수 있습니다.', '두 숟가락은 조리 도구에 나무 손잡이를 자주 쓰는 이유를 보여 줍니다.'],
                        [{word:'metal',meaning:'금속'},{word:'warm',meaning:'따뜻한'},{word:'wood',meaning:'나무, 목재'},{word:'handle',meaning:'손잡이'},{word:'comfortably',meaning:'편안하게'},{word:'heat',meaning:'열'}],
                        ['e6'],[{title:'비교급',text:'hotter와 cooler는 두 대상의 온도를 비교합니다.'}],
                        [q('er4-p0-q1','fact','Which handle feels hotter?',['the metal one','the wooden one','both equally','neither one'],0,'두 번째 문장에 금속 손잡이가 더 뜨겁다고 나옵니다.',[1]),q('er4-p0-q2','main','What does the spoon test show?',['Heat travels more easily through metal than wood.','Soup cools only with wooden spoons.','Metal spoons are made from soup.','All cooking tools should be cold.'],0,'두 재료를 비교해 열이 금속을 더 쉽게 통과함을 보여 줍니다.',[1,2,3]),q('er4-p0-q3','vocabulary','What does “handle” mean in this passage?',['the part held by a hand','to solve a hard problem','the round part in soup','a kind of warm food'],0,'숟가락에서 손으로 잡는 부분을 뜻하는 명사입니다.',[1,3]),q('er4-p0-q4','reference','What does “it” in sentence 4 refer to?',['the wooden handle','the metal spoon','the warm soup','the passing minute'],0,'문장의 주어인 the wooden handle을 가리킵니다.',[3]),q('er4-p0-q5','evidence','Which sentence explains the scientific reason for the result?',['Sentence 1','Sentence 2','Sentence 3','Sentence 5'],2,'세 번째 문장이 재료에 따른 열 이동 차이를 직접 설명합니다.',[2])]),
                    p('er4-p1','Which Paper Towel?','공정한 실험',1,
                        ['Nari wants to compare how much water two paper towels absorb.', 'She cuts equal-sized squares and pours the same amount of water into two plates.', 'Then she leaves each towel in the water for ten seconds.', 'One towel takes up more water, but Nari repeats the test three times before deciding.', 'By keeping the size, water, and time equal, she makes the comparison fair.'],
                        ['나리는 두 종이 수건이 물을 얼마나 흡수하는지 비교하려 합니다.', '그녀는 같은 크기의 정사각형을 자르고 두 접시에 같은 양의 물을 붓습니다.', '그런 다음 각각의 수건을 물에 10초 동안 둡니다.', '한 수건이 물을 더 많이 흡수하지만 나리는 결론을 내리기 전에 실험을 세 번 반복합니다.', '크기, 물, 시간을 같게 유지함으로써 그녀는 공정하게 비교합니다.'],
                        [{word:'paper',meaning:'종이'},{word:'water',meaning:'물'},{word:'time',meaning:'시간'},{word:'absorb',meaning:'흡수하다'},{word:'equal',meaning:'같은'},{word:'comparison',meaning:'비교'}],
                        ['e3','e6'],[{title:'By + -ing',text:'By keeping은 ‘~함으로써’라는 뜻으로 방법을 나타냅니다.'}],
                        [q('er4-p1-q1','fact','How long is each towel left in the water?',['ten seconds','one second','three minutes','ten minutes'],0,'세 번째 문장에 10초라고 나옵니다.',[2]),q('er4-p1-q2','main','What is the passage mainly about?',['how Nari makes a fair absorption test','why all paper towels are equal','how to dry two dinner plates','why water disappears in ten seconds'],0,'조건을 같게 하고 반복하여 공정한 비교를 하는 과정입니다.',[1,2,3,4]),q('er4-p1-q3','vocabulary','What does “absorb” mean?',['take in liquid','push away light','cut into squares','become heavier than a plate'],0,'종이 수건이 물을 빨아들이는 것을 뜻합니다.',[0,3]),q('er4-p1-q4','reference','What does “the test” in sentence 4 refer to?',['the paper-towel water comparison','cutting only one square','washing the two plates','timing a running race'],0,'앞 문장들의 두 종이 수건 흡수량 비교 실험을 가리킵니다.',[0,1,2,3]),q('er4-p1-q5','evidence','Which sentence lists the controlled conditions?',['Sentence 1','Sentence 2','Sentence 4','Sentence 5'],3,'다섯 번째 문장이 크기, 물, 시간을 동일하게 했다고 요약합니다.',[4])]),
                    p('er4-p2','The Bus-Stop Shadow','그림자와 지구의 움직임',2,
                        ['Amir watches a signpost’s shadow while he waits for the bus each morning.', 'He returns in the afternoon and sees that the shadow is shorter and points another way.', 'The post has not moved, but the sun appears in a different part of the sky.', 'This daily pattern happens because Earth rotates from west to east.', 'The changing shadow gives us a clue about a large motion that we cannot feel.'],
                        ['아미르는 매일 아침 버스를 기다리며 표지판 기둥의 그림자를 관찰합니다.', '오후에 돌아와 보니 그림자는 더 짧아졌고 다른 방향을 가리킵니다.', '기둥은 움직이지 않았지만 태양이 하늘의 다른 곳에 있는 것처럼 보입니다.', '이러한 매일의 변화는 지구가 서쪽에서 동쪽으로 자전하기 때문에 생깁니다.', '변하는 그림자는 우리가 느끼지 못하는 큰 움직임에 관한 단서를 줍니다.'],
                        [{word:'shadow',meaning:'그림자'},{word:'earth',meaning:'지구'},{word:'afternoon',meaning:'오후'},{word:'signpost',meaning:'표지판 기둥'},{word:'direction',meaning:'방향'},{word:'rotate',meaning:'자전하다, 회전하다'}],
                        ['e3','e6'],[{title:'appear + 장소 표현',text:'appears in a different part는 ‘다른 곳에 있는 것처럼 보인다’라는 뜻입니다.'}],
                        [q('er4-p2-q1','fact','How is the afternoon shadow different?',['It is shorter and points another way.','It has vanished forever.','It looks exactly the same.','It has turned into a signpost.'],0,'두 번째 문장이 방향과 길이의 변화를 밝힙니다.',[1]),q('er4-p2-q2','main','What is the central idea?',['Changing shadows can reveal Earth’s rotation.','A bus makes the sun cross the sky.','Signposts move between morning and afternoon.','Earth stops rotating at night.'],0,'관찰한 그림자의 변화가 지구 자전의 단서가 된다는 글입니다.',[1,2,3,4]),q('er4-p2-q3','vocabulary','What does “rotates” mean in sentence 4?',['turns around','stands still','grows larger','gives off light'],0,'지구가 축을 중심으로 도는 자전을 뜻합니다.',[3]),q('er4-p2-q4','reference','What does “This daily pattern” refer to?',['the regular change in the shadow','Amir missing the bus','the post moving each day','Earth becoming shorter'],0,'아침과 오후에 반복되는 그림자의 방향과 길이 변화를 가리킵니다.',[0,1,3]),q('er4-p2-q5','evidence','Which sentence directly identifies the cause of the daily pattern?',['Sentence 1','Sentence 2','Sentence 3','Sentence 4'],3,'네 번째 문장이 지구의 자전을 원인으로 직접 제시합니다.',[3])])
                ]
            }
        ]
    };
    const additions = [
        p('er1-p3', 'A Better Place to Watch', '달 관찰 장소 고르기', 2,
            ['Jin and his sister want to draw the moon after dinner.', 'They first stand beside a bright shop, but a tall building blocks their view.', 'Jin suggests a nearby park because it has an open area.', 'Before they leave, their father checks that the park is open and goes with them.', 'At the park, they can see the moon clearly above the trees.', 'His sister draws its shape while Jin writes the date and time.', 'They decide to use the same place for their next observation.'],
            ['진과 누나는 저녁 식사 후 달을 그리고 싶어 합니다.', '그들은 처음에 밝은 가게 옆에 서지만, 높은 건물이 시야를 가립니다.', '진은 탁 트인 공간이 있는 근처 공원을 제안합니다.', '출발하기 전에 아버지는 공원이 열려 있는지 확인하고 함께 갑니다.', '공원에서는 나무 위로 달을 선명하게 볼 수 있습니다.', '누나가 달의 모양을 그리는 동안 진은 날짜와 시간을 적습니다.', '그들은 다음 관찰에서도 같은 장소를 이용하기로 합니다.'],
            [{word:'moon',meaning:'달'},{word:'park',meaning:'공원'},{word:'shape',meaning:'모양'},{word:'block',meaning:'가리다, 막다'},{word:'suggest',meaning:'제안하다'},{word:'observation',meaning:'관찰'}],
            ['e3','e6'],[{title:'because와 while',text:'because는 공원을 제안한 이유를, while은 두 사람이 동시에 하는 일을 연결합니다.'}],
            [q('er1-p3-q1','fact','Why does Jin suggest the park?',['It has an open area.','It has a taller shop.','It is inside their house.','It is closed at night.'],0,'세 번째 문장에서 탁 트인 공간이 공원을 제안한 이유라고 설명합니다.',[2]),
             q('er1-p3-q2','main','What is the story mainly about?',['Choosing a suitable place to observe the moon.','Learning how to plant tall trees.','Buying a notebook at a bright shop.','Finding a new way to cook dinner.'],0,'건물에 가린 장소 대신 달을 잘 볼 수 있는 공원을 고르는 과정입니다.',[1,2,4,6]),
             q('er1-p3-q3','vocabulary','What does “blocks” mean in sentence 2?',['prevents them from seeing','helps them draw','makes the moon brighter','shows them the time'],0,'건물이 시야를 가려 달을 볼 수 없게 한다는 의미입니다.',[1]),
             q('er1-p3-q4','reference','What does “its” refer to in sentence 6?',['the moon','the shop','the park','the notebook'],0,'다섯 번째 문장에서 본 달의 모양을 누나가 그립니다.',[4,5]),
             q('er1-p3-q5','evidence','Which sentence shows that they plan to return to the park?',['Sentence 1','Sentence 3','Sentence 5','Sentence 7'],3,'일곱 번째 문장에서 다음 관찰도 같은 장소에서 하겠다고 정합니다.',[6])]),
        p('er2-p3', 'A Recipe Across the Sea', '가족과 함께 만드는 요리', 2,
            ['Sora wants to make her grandmother’s soup, but her grandmother lives far away.', 'On Saturday, they talk by video while Sora’s father helps in the kitchen.', 'Her grandmother explains each step slowly so Sora can write it down.', 'First, her father cuts the vegetables, and Sora puts them in a bowl.', 'Then he adds them to a pot of hot water.', 'When the soup is ready, Sora tastes it and smiles at the screen.', 'The family cannot share one table today, but cooking together helps them feel close.'],
            ['소라는 할머니의 수프를 만들고 싶지만, 할머니는 멀리 사십니다.', '토요일에 소라의 아버지가 부엌에서 돕는 동안 그들은 영상으로 이야기합니다.', '할머니는 소라가 적을 수 있도록 각 단계를 천천히 설명합니다.', '먼저 아버지가 채소를 썰고, 소라는 그것을 그릇에 담습니다.', '그런 다음 아버지는 채소를 뜨거운 물이 담긴 냄비에 넣습니다.', '수프가 완성되자 소라는 맛을 보고 화면을 향해 미소 짓습니다.', '가족은 오늘 한 식탁에 함께 앉을 수 없지만, 함께 요리하는 일은 그들이 가깝게 느끼도록 도와줍니다.'],
            [{word:'family',meaning:'가족'},{word:'kitchen',meaning:'부엌'},{word:'water',meaning:'물'},{word:'recipe',meaning:'요리법'},{word:'step',meaning:'단계'},{word:'pot',meaning:'냄비'}],
            ['e3','e6'],[{title:'First, Then, When',text:'First와 Then은 일의 순서를 나타냅니다. When the soup is ready는 ‘수프가 완성되면’이라는 시간 조건입니다.'}],
            [q('er2-p3-q1','fact','Who cuts the vegetables?',['Sora’s father','Sora’s grandmother','Sora’s teacher','Sora’s sister'],0,'네 번째 문장에 아버지가 채소를 썬다고 나옵니다.',[3]),
             q('er2-p3-q2','main','What is the main message?',['A shared activity can connect family members who live apart.','Every family must eat at the same table.','Writing a recipe makes food cook faster.','Video calls are only useful at school.'],0,'멀리 떨어진 가족이 영상으로 함께 요리하며 가까움을 느끼는 이야기입니다.',[0,1,6]),
             q('er2-p3-q3','vocabulary','What does “step” mean in sentence 3?',['one part of a process','a place to sit','a kind of vegetable','the sound of a call'],0,'요리법을 설명하는 문맥에서 step은 과정의 한 단계를 뜻합니다.',[2,3,4]),
             q('er2-p3-q4','reference','What does “them” refer to in sentence 5?',['the vegetables','the video calls','the family members','the written steps'],0,'그릇에 담은 채소를 아버지가 냄비에 넣습니다.',[3,4]),
             q('er2-p3-q5','evidence','Which sentence explains why the grandmother speaks slowly?',['Sentence 1','Sentence 2','Sentence 3','Sentence 6'],2,'세 번째 문장의 so Sora can write it down이 천천히 설명하는 이유입니다.',[2])]),
        p('er3-p3', 'The Lunch Box Plan', '음식 낭비 줄이기', 2,
            ['Every Friday, Leo notices fruit in the classroom’s food waste bin.', 'He asks his classmates why they throw it away.', 'Some say they bring more food than they can finish during lunch.', 'Leo suggests bringing a smaller amount first and packing extra fruit separately.', 'His classmates try the plan for one week.', 'On Friday, they compare the food waste with the amount from the week before.', 'There is less fruit in the bin, so they decide to continue the plan.', 'Leo learns that a small change in a daily habit can make a difference.'],
            ['매주 금요일 레오는 교실의 음식물 쓰레기통에서 과일을 발견합니다.', '그는 반 친구들에게 왜 과일을 버리는지 묻습니다.', '몇몇은 점심시간에 다 먹을 수 있는 양보다 많은 음식을 가져온다고 말합니다.', '레오는 우선 더 적은 양을 가져오고 여분의 과일은 따로 싸 두자고 제안합니다.', '반 친구들은 일주일 동안 그 계획을 시도합니다.', '금요일에 그들은 음식물 쓰레기를 그 전주에 나온 양과 비교합니다.', '쓰레기통에 과일이 더 적어서 그들은 계획을 계속하기로 합니다.', '레오는 일상 습관의 작은 변화가 차이를 만들 수 있다는 것을 배웁니다.'],
            [{word:'fruit',meaning:'과일'},{word:'food',meaning:'음식'},{word:'change',meaning:'변화'},{word:'waste',meaning:'쓰레기, 낭비'},{word:'amount',meaning:'양'},{word:'separately',meaning:'따로'}],
            ['e3','e6'],[{title:'비교 표현과 so',text:'more food than they can finish는 ‘다 먹을 수 있는 것보다 많은 음식’입니다. so는 관찰한 결과와 그에 따른 결정을 연결합니다.'}],
            [q('er3-p3-q1','fact','Why do some classmates throw fruit away?',['They bring more food than they can finish.','They are not allowed to eat fruit.','Leo asks them to fill the bin.','The classroom has no lunch break.'],0,'세 번째 문장에서 점심에 다 먹지 못할 만큼 많이 가져온다고 설명합니다.',[2]),
             q('er3-p3-q2','main','What is the passage mainly about?',['Testing a small change to reduce food waste.','Growing fruit in a classroom.','Buying a larger waste bin.','Making lunch breaks shorter.'],0,'먹을 양을 조절하는 계획을 실행하고 쓰레기가 줄었는지 비교하는 글입니다.',[3,4,5,6]),
             q('er3-p3-q3','vocabulary','What does “continue” mean in sentence 7?',['keep doing','stop immediately','forget about','hide from others'],0,'쓰레기가 줄어드는 효과를 보았으므로 계획을 계속한다는 뜻입니다.',[6]),
             q('er3-p3-q4','reference','What does “it” refer to in sentence 2?',['fruit','the classroom','the bin','the plan'],0,'첫 문장에서 발견한 과일을 왜 버리는지 묻습니다.',[0,1]),
             q('er3-p3-q5','evidence','Which sentence gives the clearest evidence that the plan works?',['Sentence 2','Sentence 4','Sentence 5','Sentence 7'],3,'일곱 번째 문장의 과일 쓰레기가 줄었다는 관찰이 계획의 효과를 보여 줍니다.',[6])]),
        p('er4-p3', 'Two Places for an Ice Cube', '조건을 맞춘 비교 실험', 2,
            ['Nina wants to find out where an ice cube melts faster on a sunny day.', 'She puts two ice cubes of the same size on two identical plates.', 'She leaves one plate in sunlight and the other in the shade.', 'Both plates sit on the same table, and she checks them every two minutes.', 'After ten minutes, the ice in sunlight has become a small pool of water.', 'The other plate still has a piece of ice on it.', 'Nina records the result instead of changing the cubes during the test.', 'She plans to repeat the test to see whether she gets a similar result.'],
            ['니나는 맑은 날 얼음이 어디에서 더 빨리 녹는지 알아보고 싶어 합니다.', '그녀는 크기가 같은 얼음 두 개를 똑같은 접시 두 개에 하나씩 놓습니다.', '그녀는 접시 하나를 햇빛 아래에, 다른 하나를 그늘에 둡니다.', '두 접시는 같은 탁자 위에 놓여 있고, 그녀는 2분마다 확인합니다.', '10분 후 햇빛 아래의 얼음은 녹아 작은 물웅덩이가 되었습니다.', '다른 접시에는 아직 얼음 조각이 남아 있습니다.', '니나는 실험 도중 얼음을 바꾸는 대신 결과를 기록합니다.', '그녀는 비슷한 결과가 나오는지 알아보기 위해 실험을 반복할 계획입니다.'],
            [{word:'water',meaning:'물'},{word:'table',meaning:'탁자'},{word:'sun',meaning:'태양'},{word:'melt',meaning:'녹다'},{word:'shade',meaning:'그늘'},{word:'identical',meaning:'똑같은'},{word:'repeat',meaning:'반복하다'}],
            ['e3','e6'],[{title:'one … the other와 비교급',text:'one … the other는 둘 중 ‘하나 … 나머지 하나’를 가리킵니다. faster는 fast의 비교급으로 ‘더 빨리’라는 뜻입니다.'}],
            [q('er4-p3-q1','fact','What is different about the two plates during the test?',['One is in sunlight and the other is in shade.','They hold ice cubes of different sizes.','They are checked on different days.','One is on a table and the other is on the floor.'],0,'세 번째 문장에 햇빛과 그늘이라는 위치 조건의 차이가 나옵니다.',[2]),
             q('er4-p3-q2','main','What is the passage mainly about?',['Comparing how ice melts in two different places.','Learning to make plates from ice.','Finding the best time to eat lunch.','Showing that ice never melts in shade.'],0,'같은 크기 얼음을 햇빛과 그늘에 놓고 녹는 모습을 비교하는 실험입니다.',[0,1,2,4,5]),
             q('er4-p3-q3','vocabulary','What does “identical” mean in sentence 2?',['exactly the same','very expensive','full of water','easy to break'],0,'비교 조건을 맞추기 위해 똑같은 접시를 사용한다는 뜻입니다.',[1]),
             q('er4-p3-q4','reference','What does “them” refer to in sentence 4?',['the two plates with ice','the sunny days','the tables in the room','the results in her notebook'],0,'니나는 얼음이 놓인 두 접시의 상태를 2분마다 확인합니다.',[1,2,3]),
             q('er4-p3-q5','evidence','Which pair of sentences shows that the ice in sunlight melts faster in this test?',['Sentences 1 and 2','Sentences 2 and 3','Sentences 5 and 6','Sentences 7 and 8'],2,'같은 시점에 햇빛 쪽은 물이 되었고 그늘 쪽은 얼음이 남아 있다고 비교합니다.',[4,5])])
    ];
    additions.forEach((passage, index) => window.EnglishReadingData.units[index].passages.push(passage));
})();
