var vocabHanja = {
    'level8': [
        { hanja: '一', eum: '일', meaning: '하나', radical: '一(1획)', idiom: '一石二鳥', idiomMean: '한 가지 일로 두 가지 이익을 얻음', idiomEum: '일석이조' },
        { hanja: '二', eum: '이', meaning: '둘', radical: '二(2획)', idiom: '一擧兩得', idiomMean: '한 가지 일을 하여 두 가지 이득을 얻음', idiomEum: '일거양득' },
        { hanja: '三', eum: '삼', meaning: '셋', radical: '一(3획)', idiom: '三省', idiomMean: '하루에 세 번 자신을 반성함', idiomEum: '삼성' },
        { hanja: '四', eum: '사', meaning: '넷', radical: '囗(5획)', idiom: '四方', idiomMean: '동서남북의 네 방향', idiomEum: '사방' },
        { hanja: '五', eum: '오', meaning: '다섯', radical: '二(4획)', idiom: '五感', idiomMean: '다섯 가지 감각', idiomEum: '오감' },
        { hanja: '六', eum: '육', meaning: '여섯', radical: '八(4획)', idiom: '六法', idiomMean: '여섯 가지 주요 법률', idiomEum: '육법' },
        { hanja: '七', eum: '칠', meaning: '일곱', radical: '一(2획)', idiom: '七去之惡', idiomMean: '아내를 내쫓을 수 있는 일곱 가지 이유', idiomEum: '칠거지악' },
        { hanja: '八', eum: '팔', meaning: '여덟', radical: '八(2획)', idiom: '八方美人', idiomMean: '여러 모로 보아 아름다운 사람 (다재다능)', idiomEum: '팔방미인' },
        { hanja: '九', eum: '구', meaning: '아홉', radical: '乙(2획)', idiom: '九死一生', idiomMean: '죽을 고비에서 간신히 살아남', idiomEum: '구사일생' },
        { hanja: '十', eum: '십', meaning: '열', radical: '十(2획)', idiom: '十中八九', idiomMean: '열에 여덟이나 아홉 (거의 대부분)', idiomEum: '십중팔구' },
        { hanja: '日', eum: '일', meaning: '날/해', radical: '日(4획)', antonym: '月(월)', idiom: '日進月步', idiomMean: '날로 달로 끊임없이 발전함', idiomEum: '일진월보' },
        { hanja: '月', eum: '월', meaning: '달', radical: '月(4획)', antonym: '日(일)', idiom: '月下老人', idiomMean: '남녀의 인연을 맺어주는 노인', idiomEum: '월하노인' },
        { hanja: '火', eum: '화', meaning: '불', radical: '火(4획)', antonym: '水(수)', idiom: '火中之栗', idiomMean: '불 속의 밤 (남을 위해 위험을 무릅씀)', idiomEum: '화중지율' },
        { hanja: '水', eum: '수', meaning: '물', radical: '水(4획)', antonym: '火(화)', idiom: '山戰水戰', idiomMean: '산전수전 (풍부한 경험)', idiomEum: '산전수전' },
        { hanja: '木', eum: '목', meaning: '나무', radical: '木(4획)', synonym: '樹(수)', idiom: '木石', idiomMean: '나무나 돌처럼 감정이 없는 사람', idiomEum: '목석' },
        { hanja: '金', eum: '금', meaning: '쇠/돈', radical: '金(8획)', idiom: '金科玉條', idiomMean: '금과옥조 (매우 귀중한 법률이나 규칙)', idiomEum: '금과옥조' },
        { hanja: '土', eum: '토', meaning: '흙', radical: '土(3획)', idiom: '寸土', idiomMean: '아주 적은 양의 땅', idiomEum: '촌토' },
        { hanja: '山', eum: '산', meaning: '산', radical: '山(3획)', synonym: '峰(봉)', idiom: '泰山', idiomMean: '크고 높은 산 (매우 큰 존재)', idiomEum: '태산' },
        { hanja: '靑', eum: '청', meaning: '푸르다', radical: '靑(8획)', idiom: '靑出于藍', idiomMean: '청출어람 (제자가 스승보다 나음)', idiomEum: '청출어람' },
        { hanja: '白', eum: '백', meaning: '희다', radical: '白(5획)', antonym: '黑(흑)', idiom: '白骨難忘', idiomMean: '죽어 백골이 되어도 은혜를 잊지 않음', idiomEum: '백골난망' },
        { hanja: '人', eum: '인', meaning: '사람', radical: '人(2획)', synonym: '民(민)', idiom: '人山人海', idiomMean: '사람이 산과 바다처럼 매우 많음', idiomEum: '인산인해' },
        { hanja: '民', eum: '민', meaning: '백성', radical: '氏(5획)', synonym: '人(인)', idiom: '國民', idiomMean: '나라의 주인인 백성', idiomEum: '국민' },
        { hanja: '父', eum: '부', meaning: '아버지', radical: '父(4획)', antonym: '母(모)', idiom: '父子', idiomMean: '아버지와 아들', idiomEum: '부자' },
        { hanja: '母', eum: '모', meaning: '어머니', radical: '母(5획)', antonym: '父(부)', idiom: '母校', idiomMean: '자기가 졸업한 학교', idiomEum: '모교' },
        { hanja: '兄', eum: '형', meaning: '형', radical: '儿(5획)', antonym: '弟(제)', idiom: '兄弟', idiomMean: '형과 아우 (남자 형제)', idiomEum: '형제' },
        { hanja: '弟', eum: '제', meaning: '아우', radical: '弓(7획)', antonym: '兄(형)', idiom: '弟子', idiomMean: '스승의 가르침을 받는 사람', idiomEum: '제자' },
        { hanja: '女', eum: '녀', meaning: '여자', radical: '女(3획)', antonym: '男(남)', idiom: '女子', idiomMean: '여자 (8급 기본 어휘)', idiomEum: '여자' },
        { hanja: '子', eum: '자', meaning: '아들', radical: '子(3획)', idiom: '夫子', idiomMean: '스승을 높여 부르는 말', idiomEum: '부자' },
        { hanja: '學', eum: '학', meaning: '배우다', radical: '子(16획)', synonym: '習(습)', idiom: '苦學', idiomMean: '어렵고 고생스럽게 공부함', idiomEum: '고학' },
        { hanja: '校', eum: '교', meaning: '학교', radical: '木(10획)', idiom: '學校', idiomMean: '배움을 얻는 곳', idiomEum: '학교' },
        { hanja: '先', eum: '선', meaning: '먼저', radical: '儿(6획)', antonym: '後(후)', idiom: '先見之明', idiomMean: '앞날을 미리 내다보는 밝은 눈', idiomEum: '선견지명' },
        { hanja: '生', eum: '생', meaning: '날/살다', radical: '生(5획)', antonym: '死(사)', idiom: '一生', idiomMean: '태어나서 죽을 때까지의 기간', idiomEum: '일생' },
        { hanja: '師', eum: '사', meaning: '스승', radical: '巾(10획)', synonym: '敎(교)', idiom: '恩師', idiomMean: '가르침을 주신 고마운 스승님', idiomEum: '은사' },
        { hanja: '國', eum: '국', meaning: '나라', radical: '口(11획)', synonym: '邦(방)', idiom: '萬國', idiomMean: '세상의 모든 나라', idiomEum: '만국' },
        { hanja: '韓', eum: '한', meaning: '나라', radical: '韋(18획)', idiom: '韓國', idiomMean: '대한민국 (8급 기본 어휘)', idiomEum: '한국' },
        { hanja: '軍', eum: '군', meaning: '군사', radical: '車(9획)', idiom: '軍人', idiomMean: '군대에 소속되어 나라를 지키는 사람', idiomEum: '군인' },
        { hanja: '大', eum: '대', meaning: '크다', radical: '大(3획)', antonym: '小(소)', idiom: '大器晩成', idiomMean: '큰 그릇은 늦게 만들어짐', idiomEum: '대기만성' },
        { hanja: '小', eum: '소', meaning: '작다', radical: '小(3획)', antonym: '大(대)', idiom: '小貪大失', idiomMean: '작은 것을 탐내다 큰 것을 잃음', idiomEum: '소탐대실' },
        { hanja: '中', eum: '중', meaning: '가운데', radical: '丨(4획)', idiom: '中庸', idiomMean: '지나치거나 모자람 없이 한쪽으로 치우치지 않음', idiomEum: '중용' },
        { hanja: '東', eum: '동', meaning: '동쪽', radical: '木(8획)', antonym: '西(서)', idiom: '東問西答', idiomMean: '동쪽을 묻는데 서쪽을 답함', idiomEum: '동문서답' },
        { hanja: '西', eum: '서', meaning: '서쪽', radical: '襾(6획)', antonym: '東(동)', idiom: '西遊記', idiomMean: '중국의 소설 서유기', idiomEum: '서유기' },
        { hanja: '南', eum: '남', meaning: '남쪽', radical: '十(9획)', antonym: '北(북)', idiom: '南男北女', idiomMean: '남쪽은 남자가 잘나고 북쪽은 여자가 예쁨', idiomEum: '남남북녀' },
        { hanja: '北', eum: '북', meaning: '북쪽', radical: '匕(5획)', antonym: '南(남)', idiom: '敗北', idiomMean: '싸움에서 져서 도망감', idiomEum: '패배' },
        { hanja: '上', eum: '상', meaning: '위', radical: '一(3획)', antonym: '下(하)', idiom: '上下', idiomMean: '위와 아래', idiomEum: '상하' },
        { hanja: '下', eum: '하', meaning: '아래', radical: '一(3획)', antonym: '上(상)', idiom: '下車', idiomMean: '차에서 내림', idiomEum: '하차' },
        { hanja: '口', eum: '구', meaning: '입', radical: '口(3획)', idiom: '人口', idiomMean: '한 지역에 사는 사람의 수', idiomEum: '인구' },
        { hanja: '門', eum: '문', meaning: '문', radical: '門(8획)', idiom: '校門', idiomMean: '학교의 정문', idiomEum: '교문' },
        { hanja: '年', eum: '년', meaning: '해', radical: '干(6획)', idiom: '萬年', idiomMean: '아주 오랜 세월', idiomEum: '만년' },
        { hanja: '寸', eum: '촌', meaning: '마디', radical: '寸(3획)', idiom: '三寸', idiomMean: '아버지의 형제', idiomEum: '삼촌' },
        { hanja: '王', eum: '왕', meaning: '임금', radical: '玉(4획)', idiom: '王室', idiomMean: '임금이 사는 집안', idiomEum: '왕실' }
    ],
	// 새롭게 추가되는 7급 데이터
    'level7': [
        { hanja: '家', eum: '가', meaning: '집', radical: '宀(10획)', idiom: '家和萬事成', idiomMean: '집안이 화목하면 모든 일이 잘 이루어짐', idiomEum: '가화만사성' },
        { hanja: '歌', eum: '가', meaning: '노래', radical: '欠(14획)', idiom: '高聲放歌', idiomMean: '큰 소리로 노래를 부름', idiomEum: '고성방가' },
        { hanja: '間', eum: '간', meaning: '사이', radical: '門(12획)', idiom: '兄弟之間', idiomMean: '형과 아우 사이 (가까운 사이)', idiomEum: '형제지간' },
        { hanja: '江', eum: '강', meaning: '강', radical: '水(6획)', idiom: '江山', idiomMean: '강과 산 (자연이나 영토를 뜻함)', idiomEum: '강산' },
        { hanja: '車', eum: '차', meaning: '수레', radical: '車(7획)', idiom: '自動車', idiomMean: '원동기를 장치하여 움직이는 차', idiomEum: '자동차' },
        { hanja: '工', eum: '공', meaning: '장인', radical: '工(3획)', idiom: '工事多忙', idiomMean: '공적인 일과 사적인 일로 매우 바쁨', idiomEum: '공사다망' },
        { hanja: '空', eum: '공', meaning: '빌', radical: '穴(8획)', idiom: '空手來空手去', idiomMean: '빈손으로 와서 빈손으로 감', idiomEum: '공수래공수거' },
        { hanja: '記', eum: '기', meaning: '기록할', radical: '言(10획)', idiom: '記錄', idiomMean: '후일에 남길 목적으로 어떤 사실을 적음', idiomEum: '기록' },
        { hanja: '氣', eum: '기', meaning: '기운', radical: '气(10획)', idiom: '意氣揚揚', idiomMean: '뜻한 바를 이루어 만족하고 자랑스러운 모습', idiomEum: '의기양양' },
        { hanja: '男', eum: '남', meaning: '사내', radical: '田(7획)', antonym: '女(녀)', idiom: '男女老少', idiomMean: '남자와 여자, 늙은이와 젊은이 (모든 사람)', idiomEum: '남녀노소' },
        { hanja: '內', eum: '내', meaning: '안', radical: '入(4획)', antonym: '外(외)', idiom: '內憂外患', idiomMean: '나라 안의 걱정과 밖으로부터의 근심', idiomEum: '내우외환' },
        { hanja: '農', eum: '농', meaning: '농사', radical: '辰(13획)', idiom: '農者天下之大本', idiomMean: '농사는 천하의 사람들이 살아가는 큰 근본임', idiomEum: '농자천하지대본' },
        { hanja: '答', eum: '답', meaning: '대답할', radical: '竹(12획)', antonym: '問(문)', idiom: '東問西答', idiomMean: '동쪽을 묻는데 서쪽을 대답함 (엉뚱한 대답)', idiomEum: '동문서답' },
        { hanja: '道', eum: '도', meaning: '길', radical: '辵(13획)', idiom: '言語道斷', idiomMean: '말문이 막힘 (어이가 없어서 말도 안 나옴)', idiomEum: '언어도단' },
        { hanja: '動', eum: '동', meaning: '움직일', radical: '力(11획)', antonym: '靜(정)', idiom: '輕擧妄動', idiomMean: '가볍고 망령되게 행동함', idiomEum: '경거망동' },
        { hanja: '同', eum: '동', meaning: '같을', radical: '口(6획)', antonym: '異(이)', idiom: '同病相憐', idiomMean: '같은 병을 앓는 사람끼리 서로 가엾게 여김', idiomEum: '동병상련' },
        { hanja: '冬', eum: '동', meaning: '겨울', radical: '冫(5획)', antonym: '夏(하)', idiom: '春夏秋冬', idiomMean: '봄, 여름, 가을, 겨울 (사계절)', idiomEum: '춘하추동' },
        { hanja: '洞', eum: '동', meaning: '마을', radical: '水(9획)', idiom: '洞內', idiomMean: '마을의 안', idiomEum: '동내' },
        { hanja: '理', eum: '리', meaning: '다스릴', radical: '玉(11획)', idiom: '事必歸正', idiomMean: '모든 일은 반드시 바른길로 돌아감', idiomEum: '사필귀정' },
        { hanja: '林', eum: '림', meaning: '수풀', radical: '木(8획)', idiom: '森林', idiomMean: '나무가 빽빽하게 우거진 숲', idiomEum: '삼림' },
        { hanja: '面', eum: '면', meaning: '낯', radical: '面(9획)', idiom: '面從腹背', idiomMean: '앞에서는 복종하는 체하면서 속으로는 배반함', idiomEum: '면종복배' },
        { hanja: '命', eum: '명', meaning: '목숨', radical: '口(8획)', idiom: '絶體絶命', idiomMean: '몸도 목숨도 다 된 상태 (어찌할 수 없는 막다른 지경)', idiomEum: '절체절명' },
        { hanja: '文', eum: '문', meaning: '글', radical: '文(4획)', antonym: '武(무)', idiom: '文房四友', idiomMean: '서재에 꼭 있어야 할 네 가지 벗 (종이, 붓, 먹, 벼루)', idiomEum: '문방사우' },
        { hanja: '問', eum: '문', meaning: '물을', radical: '口(11획)', antonym: '答(답)', idiom: '自問自答', idiomMean: '스스로 묻고 스스로 대답함', idiomEum: '자문자답' },
        { hanja: '物', eum: '물', meaning: '만물', radical: '牛(8획)', idiom: '萬物相', idiomMean: '온갖 물건을 다 갖추어 놓고 파는 가게', idiomEum: '만물상' },
        { hanja: '方', eum: '방', meaning: '방향', radical: '方(4획)', idiom: '四面八方', idiomMean: '사방과 팔방 (모든 방향)', idiomEum: '사면팔방' },
        { hanja: '百', eum: '백', meaning: '일백', radical: '白(6획)', idiom: '百戰百勝', idiomMean: '백 번 싸워 백 번 이김', idiomEum: '백전백승' },
        { hanja: '夫', eum: '부', meaning: '지아비', radical: '大(4획)', antonym: '婦(부)', idiom: '夫婦有別', idiomMean: '남편과 아내 사이에는 분별이 있어야 함', idiomEum: '부부유별' },
        { hanja: '不', eum: '불', meaning: '아닐', radical: '一(4획)', idiom: '不知氣數', idiomMean: '그 수를 알지 못할 정도로 많음', idiomEum: '부지기수' },
        { hanja: '事', eum: '사', meaning: '일', radical: '亅(8획)', idiom: '萬事亨通', idiomMean: '모든 일이 뜻대로 잘 풀림', idiomEum: '만사형통' },
        { hanja: '算', eum: '산', meaning: '셈할', radical: '竹(14획)', idiom: '算數', idiomMean: '셈을 하는 방법이나 과목', idiomEum: '산수' },
        { hanja: '色', eum: '색', meaning: '빛', radical: '色(6획)', idiom: '五色玲瓏', idiomMean: '다섯 가지 빛깔이 찬란하고 아름다움', idiomEum: '오색영롱' },
        { hanja: '夕', eum: '석', meaning: '저녁', radical: '夕(3획)', antonym: '朝(조)', idiom: '朝三暮四', idiomMean: '간사한 꾀로 남을 속여 희롱함', idiomEum: '조삼모사' },
        { hanja: '星', eum: '성', meaning: '별', radical: '日(9획)', idiom: '流星', idiomMean: '하늘에서 떨어지는 별 (별똥별)', idiomEum: '유성' },
        { hanja: '所', eum: '소', meaning: '곳', radical: '戶(8획)', idiom: '適材適所', idiomMean: '알맞은 인재를 알맞은 자리에 씀', idiomEum: '적재적소' },
        { hanja: '數', eum: '수', meaning: '셈', radical: '攴(15획)', idiom: '數學', idiomMean: '수량이나 공간의 성질을 연구하는 학문', idiomEum: '수학' },
        { hanja: '語', eum: '어', meaning: '말씀', radical: '言(14획)', idiom: '千言萬語', idiomMean: '수많은 말 (매우 많은 말)', idiomEum: '천언만어' },
        { hanja: '夏', eum: '하', meaning: '여름', radical: '夊(10획)', antonym: '冬(동)', idiom: '立夏', idiomMean: '여름이 시작됨을 알리는 절기', idiomEum: '입하' },
        { hanja: '秋', eum: '추', meaning: '가을', radical: '禾(9획)', antonym: '春(춘)', idiom: '千秋萬代', idiomMean: '천 년 만 년의 오랜 세월', idiomEum: '천추만대' },
        { hanja: '春', eum: '춘', meaning: '봄', radical: '日(9획)', antonym: '秋(추)', idiom: '靑春', idiomMean: '새싹이 파랗게 돋아나는 봄철 (젊은 나이)', idiomEum: '청춘' },
        { hanja: '天', eum: '천', meaning: '하늘', radical: '大(4획)', antonym: '地(지)', idiom: '天高馬肥', idiomMean: '하늘은 높고 말은 살찐다 (가을이 좋은 계절임을 뜻함)', idiomEum: '천고마비' },
        { hanja: '千', eum: '천', meaning: '일천', radical: '十(3획)', idiom: '千載一遇', idiomMean: '천 년에 한 번 만날 수 있는 좋은 기회', idiomEum: '천재일우' },
        { hanja: '草', eum: '초', meaning: '풀', radical: '艸(10획)', idiom: '草綠同色', idiomMean: '풀색과 녹색은 같은 색 (같은 무리끼리 어울림)', idiomEum: '초록동색' },
        { hanja: '村', eum: '촌', meaning: '마을', radical: '木(7획)', idiom: '農村', idiomMean: '농사짓는 사람들이 모여 사는 마을', idiomEum: '농촌' },
        { hanja: '出', eum: '출', meaning: '나갈', radical: '凵(5획)', antonym: '入(입)', idiom: '神出鬼沒', idiomMean: '귀신처럼 나타났다 사라짐 (자유자재로 나타나고 숨음)', idiomEum: '신출귀몰' },
        { hanja: '入', eum: '입', meaning: '들어올', radical: '入(2획)', antonym: '出(출)', idiom: '入學', idiomMean: '학교에 들어감', idiomEum: '입학' },
        { hanja: '休', eum: '휴', meaning: '쉴', radical: '人(6획)', idiom: '休養林', idiomMean: '편안히 쉬면서 몸과 마음을 보양할 수 있는 숲', idiomEum: '휴양림' },
        { hanja: '花', eum: '화', meaning: '꽃', radical: '艸(8획)', idiom: '落花流水', idiomMean: '떨어지는 꽃과 흐르는 물 (가는 봄의 경치, 남녀가 서로 그리워함)', idiomEum: '낙화유수' },
        { hanja: '話', eum: '화', meaning: '말씀', radical: '言(13획)', idiom: '電話', idiomMean: '멀리 있는 사람과 음성을 주고받는 통신 기기', idiomEum: '전화' },
        { hanja: '地', eum: '지', meaning: '땅', radical: '土(6획)', antonym: '天(천)', idiom: '天地創造', idiomMean: '조물주가 세상의 만물을 처음으로 만듦', idiomEum: '천지창조' },
		{ hanja: '公', eum: '공', meaning: '공평할', radical: '八(4획)', idiom: '公平無私', idiomMean: '공평하여 사사로움이 없음', idiomEum: '공평무사' },
        { hanja: '共', eum: '공', meaning: '한가지', radical: '八(6획)', idiom: '同苦同樂', idiomMean: '괴로움도 즐거움도 함께함', idiomEum: '동고동락' },
        { hanja: '果', eum: '과', meaning: '열매', radical: '木(8획)', idiom: '因果應報', idiomMean: '원인과 결과가 서로 응하여 보답함', idiomEum: '인과응보' },
        { hanja: '科', eum: '과', meaning: '과목', radical: '禾(9획)', idiom: '科學', idiomMean: '보편적인 진리나 법칙을 발견하려는 학문', idiomEum: '과학' },
        { hanja: '區', eum: '구', meaning: '구분할', radical: '匸(11획)', idiom: '區分', idiomMean: '일정한 기준에 따라 갈라 나눔', idiomEum: '구분' },
        { hanja: '球', eum: '구', meaning: '공', radical: '玉(11획)', idiom: '地球', idiomMean: '우리가 살고 있는 천체', idiomEum: '지구' },
        { hanja: '郡', eum: '군', meaning: '고을', radical: '邑(10획)', idiom: '郡守', idiomMean: '한 군(郡)의 행정을 맡아보는 우두머리', idiomEum: '군수' },
        { hanja: '近', eum: '근', meaning: '가까울', radical: '辵(7획)', antonym: '遠(원)', idiom: '近墨者黑', idiomMean: '먹을 가까이하는 사람은 검어짐', idiomEum: '근묵자흑' },
        { hanja: '根', eum: '근', meaning: '뿌리', radical: '木(10획)', idiom: '根本', idiomMean: '사물이 생겨나는 본바탕', idiomEum: '근본' },
        { hanja: '己', eum: '기', meaning: '몸', radical: '己(3획)', idiom: '克己復禮', idiomMean: '자신의 욕망을 이기고 예의를 회복함', idiomEum: '극기복례' },
        { hanja: '旗', eum: '기', meaning: '기', radical: '方(14획)', idiom: '國旗', idiomMean: '한 나라를 상징하는 기', idiomEum: '국기' },
        { hanja: '起', eum: '기', meaning: '일어날', radical: '走(10획)', idiom: '起死回生', idiomMean: '죽을 고비에서 벗어나 다시 살아남', idiomEum: '기사회생' },
        { hanja: '多', eum: '다', meaning: '많을', radical: '夕(6획)', antonym: '少(소)', idiom: '多多益善', idiomMean: '많으면 많을수록 더욱 좋음', idiomEum: '다다익선' },
        { hanja: '短', eum: '단', meaning: '짧을', radical: '矢(12획)', antonym: '長(장)', idiom: '一長一短', idiomMean: '장점도 있고 단점도 있음', idiomEum: '일장일단' },
        { hanja: '代', eum: '대', meaning: '대신할', radical: '人(5획)', idiom: '代代孫孫', idiomMean: '대대로 이어지는 자손', idiomEum: '대대손손' },
        { hanja: '對', eum: '대', meaning: '대할', radical: '寸(14획)', idiom: '對面', idiomMean: '서로 얼굴을 마주 봄', idiomEum: '대면' },
        { hanja: '圖', eum: '도', meaning: '그림', radical: '囗(14획)', idiom: '圖書館', idiomMean: '온갖 책을 모아 두고 읽게 하는 시설', idiomEum: '도서관' },
        { hanja: '度', eum: '도', meaning: '법도', radical: '广(9획)', idiom: '態度', idiomMean: '어떤 일이나 상황을 대하는 마음가짐', idiomEum: '태도' },
        { hanja: '童', eum: '동', meaning: '아이', radical: '立(12획)', idiom: '童心', idiomMean: '어린아이의 마음', idiomEum: '동심' },
        { hanja: '頭', eum: '두', meaning: '머리', radical: '頁(16획)', idiom: '頭角', idiomMean: '머리 위의 뿔 (뛰어난 재능을 드러냄)', idiomEum: '두각' },
        { hanja: '等', eum: '등', meaning: '무리', radical: '竹(12획)', idiom: '平等', idiomMean: '차별 없이 고르고 한결같음', idiomEum: '평등' },
        { hanja: '樂', eum: '락', meaning: '즐거울', radical: '木(15획)', antonym: '苦(고)', idiom: '苦盡甘來', idiomMean: '고생이 다하면 즐거움이 옴', idiomEum: '고진감래' }, // 참고: 악(음악), 락(즐거울), 요(좋아할) 3가지 음이 있음
        { hanja: '老', eum: '로', meaning: '늙을', radical: '老(6획)', antonym: '少(소)', idiom: '男女老少', idiomMean: '남녀와 노인, 아이 (모든 사람)', idiomEum: '남녀노소' },
        { hanja: '里', eum: '리', meaning: '마을', radical: '里(7획)', idiom: '千里眼', idiomMean: '천 리 밖을 보는 눈 (먼 곳의 일을 아는 능력)', idiomEum: '천리안' },
        { hanja: '立', eum: '립', meaning: '설', radical: '立(5획)', idiom: '自立', idiomMean: '남에게 의지하지 않고 스스로 섬', idiomEum: '자립' },
        { hanja: '買', eum: '매', meaning: '살', radical: '貝(12획)', antonym: '賣(매)', idiom: '買賣', idiomMean: '물건을 사고팖', idiomEum: '매매' },
        { hanja: '賣', eum: '매', meaning: '팔', radical: '貝(15획)', antonym: '買(매)', idiom: '賣國奴', idiomMean: '나라를 팔아먹은 배신자', idiomEum: '매국노' },
        { hanja: '麥', eum: '맥', meaning: '보리', radical: '麥(11획)', idiom: '麥秋', idiomMean: '보리를 거두어들이는 때 (초여름)', idiomEum: '맥추' },
        { hanja: '明', eum: '명', meaning: '밝을', radical: '日(8획)', antonym: '暗(암)', idiom: '明若觀火', idiomMean: '불을 보듯 뻔하고 명백함', idiomEum: '명약관화' },
        { hanja: '目', eum: '목', meaning: '눈', radical: '目(5획)', idiom: '刮目相對', idiomMean: '눈을 비비고 다시 봄 (학식이나 재주가 놀랍게 발전함)', idiomEum: '괄목상대' },
        { hanja: '半', eum: '반', meaning: '반', radical: '十(5획)', idiom: '半信半疑', idiomMean: '반은 믿고 반은 의심함', idiomEum: '반신반의' },
        { hanja: '番', eum: '번', meaning: '차례', radical: '田(12획)', idiom: '番號', idiomMean: '차례를 매긴 숫자', idiomEum: '번호' },
        { hanja: '本', eum: '본', meaning: '근본', radical: '木(5획)', antonym: '末(말)', idiom: '本末顚倒', idiomMean: '근본과 끝이 뒤바뀜 (일의 순서가 뒤바뀜)', idiomEum: '본말전도' },
        { hanja: '部', eum: '부', meaning: '떼', radical: '邑(11획)', idiom: '部分', idiomMean: '전체의 갈라진 일부분', idiomEum: '부분' },
        { hanja: '分', eum: '분', meaning: '나눌', radical: '八(4획)', idiom: '四分五裂', idiomMean: '넷으로 나뉘고 다섯으로 찢어짐', idiomEum: '사분오열' },
        { hanja: '死', eum: '사', meaning: '죽을', radical: '歹(6획)', antonym: '生(생)', idiom: '九死一生', idiomMean: '아홉 번 죽을 고비에서 겨우 살아남', idiomEum: '구사일생' },
        { hanja: '線', eum: '선', meaning: '줄', radical: '糸(15획)', idiom: '直線', idiomMean: '곧게 뻗은 줄이나 선', idiomEum: '직선' },
        { hanja: '雪', eum: '설', meaning: '눈', radical: '雨(11획)', idiom: '雪上加霜', idiomMean: '눈 위에 서리가 내림 (어려운 일이 겹침)', idiomEum: '설상가상' },
        { hanja: '少', eum: '소', meaning: '적을', radical: '小(4획)', antonym: '多(다)', idiom: '少數', idiomMean: '적은 수', idiomEum: '소수' },
        { hanja: '食', eum: '식', meaning: '밥/먹을', radical: '食(9획)', idiom: '食口', idiomMean: '한집에서 함께 살면서 끼니를 같이하는 사람', idiomEum: '식구' },
        { hanja: '新', eum: '신', meaning: '새', radical: '斤(13획)', antonym: '舊(구)', idiom: '溫故知新', idiomMean: '옛것을 익히고 그것을 미루어 새것을 앎', idiomEum: '온고지신' },
        { hanja: '心', eum: '심', meaning: '마음', radical: '心(4획)', idiom: '以心傳心', idiomMean: '마음과 마음으로 서로 뜻이 통함', idiomEum: '이심전심' },
        { hanja: '安', eum: '안', meaning: '편안할', radical: '宀(6획)', antonym: '危(위)', idiom: '平安', idiomMean: '근심이나 걱정이 없이 편안함', idiomEum: '평안' },
        { hanja: '夜', eum: '야', meaning: '밤', radical: '夕(8획)', antonym: '晝(주)', idiom: '晝夜', idiomMean: '낮과 밤', idiomEum: '주야' },
        { hanja: '野', eum: '야', meaning: '들', radical: '里(11획)', idiom: '野心', idiomMean: '무엇을 이루어 보려는 제 분수에 넘치는 큰 마음', idiomEum: '야심' },
        { hanja: '弱', eum: '약', meaning: '약할', radical: '弓(10획)', antonym: '强(강)', idiom: '弱肉强食', idiomMean: '약한 자의 고기를 강한 자가 먹음', idiomEum: '약육강식' },
        { hanja: '藥', eum: '약', meaning: '약', radical: '艸(19획)', idiom: '良藥苦口', idiomMean: '좋은 약은 입에 씀', idiomEum: '양약고구' },
        { hanja: '洋', eum: '양', meaning: '큰바다', radical: '水(9획)', idiom: '大洋', idiomMean: '아주 크고 넓은 바다', idiomEum: '대양' },
        { hanja: '言', eum: '언', meaning: '말씀', radical: '言(7획)', idiom: '流言蜚語', idiomMean: '근거 없이 널리 퍼진 소문', idiomEum: '유언비어' },
        { hanja: '然', eum: '연', meaning: '그러할', radical: '火(12획)', idiom: '自然', idiomMean: '사람의 힘을 더하지 않은 있는 그대로의 상태', idiomEum: '자연' }
    ],
    'level6': [
        // 준6급 신규 한자 (53자)
        { hanja: '各', eum: '각', meaning: '각각', radical: '夂(6획)', idiom: '各自圖生', idiomMean: '각자가 스스로 살아갈 방법을 도모함', idiomEum: '각자도생' },
        { hanja: '角', eum: '각', meaning: '뿔', radical: '角(7획)', idiom: '頭角', idiomMean: '머리 위의 뿔처럼 뛰어난 재능을 드러냄', idiomEum: '두각' },
        { hanja: '界', eum: '계', meaning: '지경', radical: '田(9획)', idiom: '世界', idiomMean: '지구 위의 모든 나라', idiomEum: '세계' },
        { hanja: '計', eum: '계', meaning: '셀', radical: '言(9획)', idiom: '計劃', idiomMean: '앞으로 할 일의 절차나 방법을 미리 세운 내용', idiomEum: '계획' },
        { hanja: '高', eum: '고', meaning: '높을', radical: '高(10획)', antonym: '低(저)', idiom: '高聲放歌', idiomMean: '큰 소리로 노래를 부름', idiomEum: '고성방가' },
        { hanja: '功', eum: '공', meaning: '공', radical: '力(5획)', antonym: '過(과)', idiom: '功過', idiomMean: '공과 허물', idiomEum: '공과' },
        { hanja: '光', eum: '광', meaning: '빛', radical: '儿(6획)', idiom: '光明正大', idiomMean: '언행이 떳떳하고 정당함', idiomEum: '광명정대' },
        { hanja: '今', eum: '금', meaning: '이제', radical: '人(4획)', antonym: '古(고)', idiom: '今時初聞', idiomMean: '지금 처음으로 들음', idiomEum: '금시초문' },
        { hanja: '急', eum: '급', meaning: '급할', radical: '心(9획)', antonym: '緩(완)', idiom: '焦急', idiomMean: '몹시 조급하게 굶', idiomEum: '초급' },
        { hanja: '堂', eum: '당', meaning: '집', radical: '土(11획)', idiom: '堂堂', idiomMean: '거리낌 없이 떳떳함', idiomEum: '당당' },
        { hanja: '讀', eum: '독', meaning: '읽을', radical: '言(22획)', idiom: '多讀', idiomMean: '책을 많이 읽음', idiomEum: '다독' },
        { hanja: '利', eum: '리', meaning: '이로울', radical: '刀(7획)', antonym: '害(해)', idiom: '利用厚生', idiomMean: '물자를 잘 이용하여 백성의 생활을 넉넉하게 함', idiomEum: '이용후생' },
        { hanja: '聞', eum: '문', meaning: '들을', radical: '耳(14획)', idiom: '博學多聞', idiomMean: '배움이 넓고 아는 것이 많음', idiomEum: '박학다문' },
        { hanja: '反', eum: '반', meaning: '돌이킬', radical: '又(4획)', idiom: '反面敎師', idiomMean: '부정적인 면에서 오히려 가르침을 주는 스승', idiomEum: '반면교사' },
        { hanja: '班', eum: '반', meaning: '나눌', radical: '玉(10획)', idiom: '班長', idiomMean: '한 반의 우두머리', idiomEum: '반장' },
        { hanja: '發', eum: '발', meaning: '필', radical: '癶(12획)', idiom: '發展', idiomMean: '더 낫고 좋은 상태나 높은 단계로 나아감', idiomEum: '발전' },
        { hanja: '放', eum: '방', meaning: '놓을', radical: '攴(8획)', idiom: '放心', idiomMean: '마음을 놓아 버려 조심하지 않음', idiomEum: '방심' },
        { hanja: '社', eum: '사', meaning: '모일', radical: '示(8획)', idiom: '社會', idiomMean: '같은 무리끼리 모여 이루는 집단', idiomEum: '사회' },
        { hanja: '書', eum: '서', meaning: '글', radical: '曰(10획)', idiom: '書堂', idiomMean: '글을 가르치던 사설 교육 기관', idiomEum: '서당' },
        { hanja: '成', eum: '성', meaning: '이룰', radical: '戈(7획)', antonym: '敗(패)', idiom: '成功', idiomMean: '원하는 바를 이룸', idiomEum: '성공' },
        { hanja: '省', eum: '성', meaning: '살필', radical: '目(9획)', idiom: '反省', idiomMean: '자신의 언행을 돌이켜 봄', idiomEum: '반성' },
        { hanja: '消', eum: '소', meaning: '사라질', radical: '水(10획)', idiom: '消滅', idiomMean: '사라져 없어짐', idiomEum: '소멸' },
        { hanja: '術', eum: '술', meaning: '재주', radical: '行(11획)', idiom: '武術', idiomMean: '무예에 관한 기술', idiomEum: '무술' },
        { hanja: '始', eum: '시', meaning: '비로소', radical: '女(8획)', antonym: '終(종)', idiom: '始終一貫', idiomMean: '처음부터 끝까지 한결같음', idiomEum: '시종일관' },
        { hanja: '身', eum: '신', meaning: '몸', radical: '身(7획)', idiom: '身言書判', idiomMean: '인물 평가 기준인 체모·언변·문필·판단력 네 가지', idiomEum: '신언서판' },
        { hanja: '神', eum: '신', meaning: '귀신', radical: '示(10획)', idiom: '神出鬼沒', idiomMean: '귀신처럼 자유자재로 나타났다 사라짐', idiomEum: '신출귀몰' },
        { hanja: '信', eum: '신', meaning: '믿을', radical: '人(9획)', idiom: '信賞必罰', idiomMean: '공이 있으면 반드시 상을 주고 죄가 있으면 반드시 벌을 줌', idiomEum: '신상필벌' },
        { hanja: '業', eum: '업', meaning: '업', radical: '木(13획)', idiom: '家業', idiomMean: '집안 대대로 이어 내려오는 직업이나 재산', idiomEum: '가업' },
        { hanja: '勇', eum: '용', meaning: '날랠', radical: '力(9획)', antonym: '怯(겁)', idiom: '勇猛精進', idiomMean: '용감하고 씩씩하게 힘써 나아감', idiomEum: '용맹정진' },
        { hanja: '用', eum: '용', meaning: '쓸', radical: '用(5획)', idiom: '用意周到', idiomMean: '준비가 두루 잘 갖추어져 있음', idiomEum: '용의주도' },
        { hanja: '運', eum: '운', meaning: '옮길', radical: '辵(13획)', idiom: '運命', idiomMean: '인간의 의지와 무관하게 정해진 삶의 앞날', idiomEum: '운명' },
        { hanja: '音', eum: '음', meaning: '소리', radical: '音(9획)', synonym: '聲(성)', idiom: '音信不通', idiomMean: '소식이나 연락이 전혀 없음', idiomEum: '음신불통' },
        { hanja: '飮', eum: '음', meaning: '마실', radical: '食(13획)', idiom: '飮食', idiomMean: '먹고 마심, 또는 그 음식', idiomEum: '음식' },
        { hanja: '意', eum: '의', meaning: '뜻', radical: '心(13획)', idiom: '意志', idiomMean: '어떤 일을 이루고자 하는 마음', idiomEum: '의지' },
        { hanja: '作', eum: '작', meaning: '지을', radical: '人(7획)', idiom: '作心三日', idiomMean: '결심이 사흘을 가지 못함', idiomEum: '작심삼일' },
        { hanja: '昨', eum: '작', meaning: '어제', radical: '日(9획)', idiom: '昨今', idiomMean: '어제와 오늘', idiomEum: '작금' },
        { hanja: '才', eum: '재', meaning: '재주', radical: '手(3획)', idiom: '才子多病', idiomMean: '재주가 뛰어난 사람은 몸이 약한 경우가 많음', idiomEum: '재자다병' },
        { hanja: '戰', eum: '전', meaning: '싸움', radical: '戈(16획)', idiom: '百戰百勝', idiomMean: '백 번 싸워 백 번 이김', idiomEum: '백전백승' },
        { hanja: '庭', eum: '정', meaning: '뜰', radical: '广(10획)', idiom: '家庭', idiomMean: '한 가족이 살고 있는 집', idiomEum: '가정' },
        { hanja: '第', eum: '제', meaning: '차례', radical: '竹(11획)', idiom: '第一', idiomMean: '가장 먼저이거나 으뜸', idiomEum: '제일' },
        { hanja: '題', eum: '제', meaning: '제목', radical: '頁(18획)', idiom: '題目', idiomMean: '글이나 작품의 이름', idiomEum: '제목' },
        { hanja: '注', eum: '주', meaning: '부을', radical: '水(8획)', idiom: '注意', idiomMean: '마음에 새겨 두어 조심함', idiomEum: '주의' },
        { hanja: '集', eum: '집', meaning: '모을', radical: '隹(12획)', idiom: '集中', idiomMean: '한 곳에 모아 집중함', idiomEum: '집중' },
        { hanja: '窓', eum: '창', meaning: '창', radical: '穴(11획)', idiom: '同窓', idiomMean: '같은 학교에서 공부한 사이', idiomEum: '동창' },
        { hanja: '淸', eum: '청', meaning: '맑을', radical: '水(11획)', antonym: '濁(탁)', idiom: '淸廉', idiomMean: '마음이 맑고 깨끗하며 탐욕이 없음', idiomEum: '청렴' },
        { hanja: '體', eum: '체', meaning: '몸', radical: '骨(23획)', idiom: '體面', idiomMean: '남을 대할 만한 체면이나 명예', idiomEum: '체면' },
        { hanja: '表', eum: '표', meaning: '겉', radical: '衣(8획)', antonym: '裏(리)', idiom: '表裏不同', idiomMean: '겉과 속이 다름', idiomEum: '표리부동' },
        { hanja: '風', eum: '풍', meaning: '바람', radical: '風(9획)', idiom: '風前燈火', idiomMean: '바람 앞의 등불처럼 매우 위태로운 처지', idiomEum: '풍전등화' },
        { hanja: '幸', eum: '행', meaning: '다행', radical: '干(8획)', antonym: '不幸(불행)', idiom: '幸運', idiomMean: '좋은 운수', idiomEum: '행운' },
        { hanja: '現', eum: '현', meaning: '나타날', radical: '玉(11획)', idiom: '現在', idiomMean: '지금 이 시간', idiomEum: '현재' },
        { hanja: '形', eum: '형', meaning: '모양', radical: '彡(7획)', idiom: '形形色色', idiomMean: '모양과 빛깔이 가지가지로 다름', idiomEum: '형형색색' },
        { hanja: '和', eum: '화', meaning: '화할', radical: '口(8획)', antonym: '爭(쟁)', idiom: '和氣靄靄', idiomMean: '화목한 기운이 가득함', idiomEum: '화기애애' },
        { hanja: '會', eum: '회', meaning: '모일', radical: '人(13획)', idiom: '社會', idiomMean: '같은 무리끼리 모여 이루는 집단', idiomEum: '사회' },
        // 6급 신규 한자 (60자)
        { hanja: '感', eum: '감', meaning: '느낄', radical: '心(13획)', idiom: '感謝', idiomMean: '고마움을 느껴 감사히 여김', idiomEum: '감사' },
        { hanja: '強', eum: '강', meaning: '강할', radical: '弓(12획)', antonym: '弱(약)', idiom: '自强不息', idiomMean: '스스로 힘써 쉬지 않고 노력함', idiomEum: '자강불식' },
        { hanja: '開', eum: '개', meaning: '열', radical: '門(12획)', antonym: '閉(폐)', idiom: '開天節', idiomMean: '하늘이 열린 날, 우리나라의 건국 기념일', idiomEum: '개천절' },
        { hanja: '京', eum: '경', meaning: '서울', radical: '亠(8획)', idiom: '上京', idiomMean: '서울로 올라감', idiomEum: '상경' },
        { hanja: '古', eum: '고', meaning: '옛', radical: '口(5획)', antonym: '今(금)', idiom: '古今東西', idiomMean: '예와 지금, 동양과 서양을 통틀어 이름', idiomEum: '고금동서' },
        { hanja: '苦', eum: '고', meaning: '쓸', radical: '艸(9획)', antonym: '甘(감)', idiom: '苦盡甘來', idiomMean: '고생이 다하면 즐거움이 옴', idiomEum: '고진감래' },
        { hanja: '交', eum: '교', meaning: '사귈', radical: '亠(6획)', idiom: '外交', idiomMean: '다른 나라와 관계를 맺음', idiomEum: '외교' },
        { hanja: '級', eum: '급', meaning: '등급', radical: '糸(10획)', idiom: '上級', idiomMean: '더 높은 등급이나 단계', idiomEum: '상급' },
        { hanja: '待', eum: '대', meaning: '기다릴', radical: '彳(9획)', idiom: '期待', idiomMean: '어떤 일이 원하는 대로 되기를 바라며 기다림', idiomEum: '기대' },
        { hanja: '例', eum: '례', meaning: '법식', radical: '人(8획)', idiom: '例外', idiomMean: '일반적인 규칙이나 원칙에서 벗어난 것', idiomEum: '예외' },
        { hanja: '禮', eum: '례', meaning: '예도', radical: '示(18획)', idiom: '禮義廉恥', idiomMean: '예의, 의리, 청렴, 부끄러움의 네 가지 덕목', idiomEum: '예의염치' },
        { hanja: '路', eum: '로', meaning: '길', radical: '足(13획)', idiom: '進退兩難', idiomMean: '나아가기도 물러서기도 어려운 처지', idiomEum: '진퇴양난' },
        { hanja: '綠', eum: '록', meaning: '푸를', radical: '糸(14획)', idiom: '綠陰芳草', idiomMean: '푸른 나무 그늘과 향기로운 풀', idiomEum: '녹음방초' },
        { hanja: '李', eum: '리', meaning: '오얏/성', radical: '木(7획)', idiom: '桃李', idiomMean: '복숭아와 자두, 또는 제자를 뜻함', idiomEum: '도리' },
        { hanja: '美', eum: '미', meaning: '아름다울', radical: '羊(9획)', antonym: '醜(추)', idiom: '美風良俗', idiomMean: '아름다운 풍속과 좋은 습관', idiomEum: '미풍양속' },
        { hanja: '米', eum: '미', meaning: '쌀', radical: '米(6획)', idiom: '白米', idiomMean: '껍질을 벗겨 하얗게 만든 쌀', idiomEum: '백미' },
        { hanja: '朴', eum: '박', meaning: '성', radical: '木(6획)', idiom: '素朴', idiomMean: '꾸밈이나 거짓이 없이 자연 그대로의 상태', idiomEum: '소박' },
        { hanja: '別', eum: '별', meaning: '다를', radical: '刀(7획)', antonym: '合(합)', idiom: '別有天地', idiomMean: '딴 세상이 따로 있음, 경치가 매우 아름다운 곳', idiomEum: '별유천지' },
        { hanja: '病', eum: '병', meaning: '병', radical: '疒(10획)', idiom: '同病相憐', idiomMean: '같은 병을 앓는 사람끼리 서로 가엾게 여김', idiomEum: '동병상련' },
        { hanja: '服', eum: '복', meaning: '옷', radical: '月(8획)', idiom: '服從', idiomMean: '남의 명령이나 의사에 따름', idiomEum: '복종' },
        { hanja: '使', eum: '사', meaning: '부릴', radical: '人(8획)', idiom: '使命', idiomMean: '맡겨진 임무', idiomEum: '사명' },
        { hanja: '席', eum: '석', meaning: '자리', radical: '巾(10획)', idiom: '出席', idiomMean: '모임이나 자리에 참석함', idiomEum: '출석' },
        { hanja: '石', eum: '석', meaning: '돌', radical: '石(5획)', idiom: '一石二鳥', idiomMean: '돌 하나로 새 두 마리를 잡음', idiomEum: '일석이조' },
        { hanja: '速', eum: '속', meaning: '빠를', radical: '辵(11획)', antonym: '遲(지)', idiom: '速戰速決', idiomMean: '빨리 싸워 빨리 결판을 냄', idiomEum: '속전속결' },
        { hanja: '孫', eum: '손', meaning: '손자', radical: '子(10획)', idiom: '子孫萬代', idiomMean: '자손이 오래도록 이어짐', idiomEum: '자손만대' },
        { hanja: '樹', eum: '수', meaning: '나무', radical: '木(16획)', synonym: '木(목)', idiom: '十年樹木', idiomMean: '나무를 키우는 데는 십 년이 걸림', idiomEum: '십년수목' },
        { hanja: '習', eum: '습', meaning: '익힐', radical: '羽(11획)', idiom: '溫故知新', idiomMean: '옛것을 익히고 새것을 앎', idiomEum: '온고지신' },
        { hanja: '勝', eum: '승', meaning: '이길', radical: '力(12획)', antonym: '敗(패)', idiom: '百戰百勝', idiomMean: '백 번 싸워 백 번 이김', idiomEum: '백전백승' },
        { hanja: '式', eum: '식', meaning: '법', radical: '工(6획)', idiom: '入學式', idiomMean: '학교에 입학하는 의식', idiomEum: '입학식' },
        { hanja: '失', eum: '실', meaning: '잃을', radical: '大(5획)', antonym: '得(득)', idiom: '失敗', idiomMean: '일을 잘못하여 그르침', idiomEum: '실패' },
        { hanja: '愛', eum: '애', meaning: '사랑', radical: '心(13획)', idiom: '愛國', idiomMean: '자기 나라를 사랑함', idiomEum: '애국' },
        { hanja: '陽', eum: '양', meaning: '볕', radical: '阜(12획)', antonym: '陰(음)', idiom: '陽春', idiomMean: '따뜻한 봄철', idiomEum: '양춘' },
        { hanja: '英', eum: '영', meaning: '꽃부리', radical: '艸(9획)', idiom: '英才', idiomMean: '뛰어난 재주를 가진 사람', idiomEum: '영재' },
        { hanja: '永', eum: '영', meaning: '길', radical: '水(5획)', idiom: '永遠', idiomMean: '어느 때까지나 변하지 않고 계속되는 것', idiomEum: '영원' },
        { hanja: '溫', eum: '온', meaning: '따뜻할', radical: '水(13획)', antonym: '冷(냉)', idiom: '溫故知新', idiomMean: '옛것을 익히고 그것을 미루어 새것을 앎', idiomEum: '온고지신' },
        { hanja: '園', eum: '원', meaning: '동산', radical: '囗(13획)', idiom: '樂園', idiomMean: '즐거움이 가득한 곳', idiomEum: '낙원' },
        { hanja: '遠', eum: '원', meaning: '멀', radical: '辵(14획)', antonym: '近(근)', idiom: '遠交近攻', idiomMean: '먼 나라와 사귀고 가까운 나라를 공격함', idiomEum: '원교근공' },
        { hanja: '由', eum: '유', meaning: '말미암을', radical: '田(5획)', idiom: '自由', idiomMean: '자기 마음대로 행동할 수 있는 상태', idiomEum: '자유' },
        { hanja: '油', eum: '유', meaning: '기름', radical: '水(8획)', idiom: '石油', idiomMean: '땅속에서 나오는 기름', idiomEum: '석유' },
        { hanja: '銀', eum: '은', meaning: '은', radical: '金(14획)', idiom: '銀行', idiomMean: '돈을 맡기고 빌려주는 금융 기관', idiomEum: '은행' },
        { hanja: '醫', eum: '의', meaning: '의원', radical: '酉(18획)', idiom: '醫師', idiomMean: '의술로 병을 고치는 사람', idiomEum: '의사' },
        { hanja: '衣', eum: '의', meaning: '옷', radical: '衣(6획)', idiom: '衣食住', idiomMean: '입고 먹고 사는 세 가지 생활 요소', idiomEum: '의식주' },
        { hanja: '者', eum: '자', meaning: '놈', radical: '老(9획)', idiom: '當事者', idiomMean: '일에 직접 관계가 있는 사람', idiomEum: '당사자' },
        { hanja: '章', eum: '장', meaning: '글', radical: '立(11획)', idiom: '文章', idiomMean: '생각이나 감정을 글로 표현한 것', idiomEum: '문장' },
        { hanja: '在', eum: '재', meaning: '있을', radical: '土(6획)', idiom: '現在', idiomMean: '지금 이 시간', idiomEum: '현재' },
        { hanja: '定', eum: '정', meaning: '정할', radical: '宀(8획)', idiom: '決定', idiomMean: '행동이나 태도를 분명히 결정함', idiomEum: '결정' },
        { hanja: '朝', eum: '조', meaning: '아침', radical: '月(12획)', antonym: '夕(석)', idiom: '朝三暮四', idiomMean: '간사한 꾀로 남을 속임', idiomEum: '조삼모사' },
        { hanja: '族', eum: '족', meaning: '겨레', radical: '方(11획)', idiom: '民族', idiomMean: '같은 지역에서 역사적으로 형성된 사람의 집단', idiomEum: '민족' },
        { hanja: '晝', eum: '주', meaning: '낮', radical: '日(11획)', antonym: '夜(야)', idiom: '晝夜長川', idiomMean: '밤낮으로 쉬지 않고 계속됨', idiomEum: '주야장천' },
        { hanja: '親', eum: '친', meaning: '친할', radical: '見(16획)', idiom: '親舊', idiomMean: '오래 사귀어 친한 사람', idiomEum: '친구' },
        { hanja: '太', eum: '태', meaning: '클', radical: '大(4획)', idiom: '太平', idiomMean: '근심 없이 편안함', idiomEum: '태평' },
        { hanja: '通', eum: '통', meaning: '통할', radical: '辵(11획)', idiom: '通信', idiomMean: '소식을 전하고 받음', idiomEum: '통신' },
        { hanja: '特', eum: '특', meaning: '특별할', radical: '牛(10획)', idiom: '特別', idiomMean: '보통과 구별되게 다름', idiomEum: '특별' },
        { hanja: '合', eum: '합', meaning: '합할', radical: '口(6획)', antonym: '分(분)', idiom: '合同', idiomMean: '여럿이 합하여 하나가 됨', idiomEum: '합동' },
        { hanja: '行', eum: '행', meaning: '다닐', radical: '行(6획)', idiom: '行動', idiomMean: '몸을 움직여 행하는 동작이나 일', idiomEum: '행동' },
        { hanja: '向', eum: '향', meaning: '향할', radical: '口(6획)', idiom: '向上', idiomMean: '더 높은 단계로 나아감', idiomEum: '향상' },
        { hanja: '號', eum: '호', meaning: '이름', radical: '虍(13획)', idiom: '番號', idiomMean: '차례를 나타내는 숫자', idiomEum: '번호' },
        { hanja: '畫', eum: '화', meaning: '그림', radical: '田(12획)', idiom: '畫龍點睛', idiomMean: '용을 그리고 눈을 찍음, 가장 중요한 부분을 마무리함', idiomEum: '화룡점정' },
        { hanja: '黃', eum: '황', meaning: '누를', radical: '黃(12획)', idiom: '黃金', idiomMean: '누런 빛의 귀한 쇠', idiomEum: '황금' },
        { hanja: '訓', eum: '훈', meaning: '가르칠', radical: '言(10획)', idiom: '訓長', idiomMean: '서당에서 아이들을 가르치는 사람', idiomEum: '훈장' }
    ]
};
