var vocabHanja = {
    'level8': [
        { hanja: '一', eum: '일', meaning: '하나', radical: '一(1획)', idiom: '一石二鳥', idiomMean: '한 가지 일로 두 가지 이익을 얻음', idiomEum: '일석이조' },
        { hanja: '二', eum: '이', meaning: '둘', radical: '二(2획)', idiom: '一擧兩得', idiomMean: '한 가지 일을 하여 두 가지 이득을 얻음', idiomEum: '일거양득' },
        { hanja: '三', eum: '삼', meaning: '셋', radical: '一(3획)', idiom: '三省', idiomMean: '하루에 세 번 자신을 반성함', idiomEum: '삼성' },
        { hanja: '四', eum: '사', meaning: '넷', radical: '囗(5획)', idiom: '四方', idiomMean: '동서남북의 네 방향', idiomEum: '사방' },
        { hanja: '五', eum: '오', meaning: '다섯', radical: '二(4획)', idiom: '五感', idiomMean: '다섯 가지 감각', idiomEum: '오감' },
        { hanja: '六', eum: '육', meaning: '여섯', radical: '八(4획)', idiom: '六法', idiomMean: '여섯 가지 주요 법률', idiomEum: '육법' },
        { hanja: '七', eum: '칠', meaning: '일곱', radical: '一(2획)', idiom: '七去之惡', idiomMean: '아내를 내쫓을 수 있는 일곱 가지 이유', idiomEum: '칠거지악' },
        { hanja: '八', eum: '팔', meaning: '여덟', radical: '八(2획)', idiom: '八方美人', idiomMean: '여러 모로 보아 아름다운 사람 (다재다능)', idiomEum: '팔방미인' },
        { hanja: '九', eum: '구', meaning: '아홉', radical: '乙(2획)', idiom: '九死一生', idiomMean: '죽을 고비에서 간신히 살아남', idiomEum: '구사일생' },
        { hanja: '十', eum: '십', meaning: '열', radical: '十(2획)', idiom: '十中八九', idiomMean: '열에 여덟이나 아홉 (거의 대부분)', idiomEum: '십중팔구' },
        { hanja: '日', eum: '일', meaning: '날/해', radical: '日(4획)', antonym: '月(월)', idiom: '日進月步', idiomMean: '날로 달로 끊임없이 발전함', idiomEum: '일진월보' },
        { hanja: '月', eum: '월', meaning: '달', radical: '月(4획)', antonym: '日(일)', idiom: '月下老人', idiomMean: '남녀의 인연을 맺어주는 노인', idiomEum: '월하노인' },
        { hanja: '火', eum: '화', meaning: '불', radical: '火(4획)', antonym: '水(수)', idiom: '火中之栗', idiomMean: '불 속의 밤 (남을 위해 위험을 무릅씀)', idiomEum: '화중지율' },
        { hanja: '水', eum: '수', meaning: '물', radical: '水(4획)', antonym: '火(화)', idiom: '山戰水戰', idiomMean: '산전수전 (풍부한 경험)', idiomEum: '산전수전' },
        { hanja: '木', eum: '목', meaning: '나무', radical: '木(4획)', synonym: '樹(수)', idiom: '木石', idiomMean: '나무나 돌처럼 감정이 없는 사람', idiomEum: '목석' },
        { hanja: '金', eum: '금', meaning: '쇠/돈', radical: '金(8획)', idiom: '金科玉條', idiomMean: '금과옥조 (매우 귀중한 법률이나 규칙)', idiomEum: '금과옥조' },
        { hanja: '土', eum: '토', meaning: '흙', radical: '土(3획)', idiom: '寸土', idiomMean: '아주 적은 양의 땅', idiomEum: '촌토' },
        { hanja: '山', eum: '산', meaning: '산', radical: '山(3획)', synonym: '峰(봉)', idiom: '泰山', idiomMean: '크고 높은 산 (매우 큰 존재)', idiomEum: '태산' },
        { hanja: '靑', eum: '청', meaning: '푸르다', radical: '靑(8획)', idiom: '靑出于藍', idiomMean: '청출어람 (제자가 스승보다 나음)', idiomEum: '청출어람' },
        { hanja: '白', eum: '백', meaning: '희다', radical: '白(5획)', antonym: '黑(흑)', idiom: '白骨難忘', idiomMean: '죽어 백골이 되어도 은혜를 잊지 않음', idiomEum: '백골난망' },
        { hanja: '人', eum: '인', meaning: '사람', radical: '人(2획)', synonym: '民(민)', idiom: '人山人海', idiomMean: '사람이 산과 바다처럼 매우 많음', idiomEum: '인산인해' },
        { hanja: '民', eum: '민', meaning: '백성', radical: '氏(5획)', synonym: '人(인)', idiom: '國民', idiomMean: '나라의 주인인 백성', idiomEum: '국민' },
        { hanja: '父', eum: '부', meaning: '아버지', radical: '父(4획)', antonym: '母(모)', idiom: '父子', idiomMean: '아버지와 아들', idiomEum: '부자' },
        { hanja: '母', eum: '모', meaning: '어머니', radical: '母(5획)', antonym: '父(부)', idiom: '母校', idiomMean: '자기가 졸업한 학교', idiomEum: '모교' },
        { hanja: '兄', eum: '형', meaning: '형', radical: '儿(5획)', antonym: '弟(제)', idiom: '兄弟', idiomMean: '형과 아우 (남자 형제)', idiomEum: '형제' },
        { hanja: '弟', eum: '제', meaning: '아우', radical: '弓(7획)', antonym: '兄(형)', idiom: '弟子', idiomMean: '스승의 가르침을 받는 사람', idiomEum: '제자' },
        { hanja: '女', eum: '녀', meaning: '여자', radical: '女(3획)', antonym: '男(남)', idiom: '女子', idiomMean: '여자 (8급 기본 어휘)', idiomEum: '여자' },
        { hanja: '子', eum: '자', meaning: '아들', radical: '子(3획)', idiom: '夫子', idiomMean: '스승을 높여 부르는 말', idiomEum: '부자' },
        { hanja: '學', eum: '학', meaning: '배우다', radical: '子(16획)', synonym: '習(습)', idiom: '苦學', idiomMean: '어렵고 고생스럽게 공부함', idiomEum: '고학' },
        { hanja: '校', eum: '교', meaning: '학교', radical: '木(10획)', idiom: '學校', idiomMean: '배움을 얻는 곳', idiomEum: '학교' },
        { hanja: '先', eum: '선', meaning: '먼저', radical: '儿(6획)', antonym: '後(후)', idiom: '先見之明', idiomMean: '앞날을 미리 내다보는 밝은 눈', idiomEum: '선견지명' },
        { hanja: '生', eum: '생', meaning: '날/살다', radical: '生(5획)', antonym: '死(사)', idiom: '一生', idiomMean: '태어나서 죽을 때까지의 기간', idiomEum: '일생' },
        { hanja: '師', eum: '사', meaning: '스승', radical: '巾(10획)', synonym: '敎(교)', idiom: '恩師', idiomMean: '가르침을 주신 고마운 스승님', idiomEum: '은사' },
        { hanja: '國', eum: '국', meaning: '나라', radical: '口(11획)', synonym: '邦(방)', idiom: '萬國', idiomMean: '세상의 모든 나라', idiomEum: '만국' },
        { hanja: '韓', eum: '한', meaning: '나라', radical: '韋(18획)', idiom: '韓國', idiomMean: '대한민국 (8급 기본 어휘)', idiomEum: '한국' },
        { hanja: '軍', eum: '군', meaning: '군사', radical: '車(9획)', idiom: '軍人', idiomMean: '군대에 소속되어 나라를 지키는 사람', idiomEum: '군인' },
        { hanja: '大', eum: '대', meaning: '크다', radical: '大(3획)', antonym: '小(소)', idiom: '大器晩成', idiomMean: '큰 그릇은 늦게 만들어짐', idiomEum: '대기만성' },
        { hanja: '小', eum: '소', meaning: '작다', radical: '小(3획)', antonym: '大(대)', idiom: '小貪大失', idiomMean: '작은 것을 탐내다 큰 것을 잃음', idiomEum: '소탐대실' },
        { hanja: '中', eum: '중', meaning: '가운데', radical: '丨(4획)', idiom: '中庸', idiomMean: '지나치거나 모자람 없이 한쪽으로 치우치지 않음', idiomEum: '중용' },
        { hanja: '東', eum: '동', meaning: '동쪽', radical: '木(8획)', antonym: '西(서)', idiom: '東問西答', idiomMean: '동쪽을 묻는데 서쪽을 답함', idiomEum: '동문서답' },
        { hanja: '西', eum: '서', meaning: '서쪽', radical: '襾(6획)', antonym: '東(동)', idiom: '西遊記', idiomMean: '중국의 소설 서유기', idiomEum: '서유기' },
        { hanja: '南', eum: '남', meaning: '남쪽', radical: '十(9획)', antonym: '北(북)', idiom: '南男北女', idiomMean: '남쪽은 남자가 잘나고 북쪽은 여자가 예쁨', idiomEum: '남남북녀' },
        { hanja: '北', eum: '북', meaning: '북쪽', radical: '匕(5획)', antonym: '南(남)', idiom: '敗北', idiomMean: '싸움에서 져서 도망감', idiomEum: '패배' },
        { hanja: '上', eum: '상', meaning: '위', radical: '一(3획)', antonym: '下(하)', idiom: '上下', idiomMean: '위와 아래', idiomEum: '상하' },
        { hanja: '下', eum: '하', meaning: '아래', radical: '一(3획)', antonym: '上(상)', idiom: '下車', idiomMean: '차에서 내림', idiomEum: '하차' },
        { hanja: '口', eum: '구', meaning: '입', radical: '口(3획)', idiom: '人口', idiomMean: '한 지역에 사는 사람의 수', idiomEum: '인구' },
        { hanja: '門', eum: '문', meaning: '문', radical: '門(8획)', idiom: '校門', idiomMean: '학교의 정문', idiomEum: '교문' },
        { hanja: '年', eum: '년', meaning: '해', radical: '干(6획)', idiom: '萬年', idiomMean: '아주 오랜 세월', idiomEum: '만년' },
        { hanja: '寸', eum: '촌', meaning: '마디', radical: '寸(3획)', idiom: '三寸', idiomMean: '아버지의 형제', idiomEum: '삼촌' },
        { hanja: '王', eum: '왕', meaning: '임금', radical: '玉(4획)', idiom: '王室', idiomMean: '임금이 사는 집안', idiomEum: '왕실' }
    ],
	// 새롭게 추가되는 7급 데이터
    'level7': [
        { hanja: '家', eum: '가', meaning: '집', radical: '宀(10획)', idiom: '家和萬事成', idiomMean: '집안이 화목하면 모든 일이 잘 이루어짐', idiomEum: '가화만사성' },
        { hanja: '歌', eum: '가', meaning: '노래', radical: '欠(14획)', idiom: '高聲放歌', idiomMean: '큰 소리로 노래를 부름', idiomEum: '고성방가' },
        { hanja: '間', eum: '간', meaning: '사이', radical: '門(12획)', idiom: '兄弟之間', idiomMean: '형과 아우 사이 (가까운 사이)', idiomEum: '형제지간' },
        { hanja: '江', eum: '강', meaning: '강', radical: '水(6획)', idiom: '江山', idiomMean: '강과 산 (자연이나 영토를 뜻함)', idiomEum: '강산' },
        { hanja: '車', eum: '차', meaning: '수레', radical: '車(7획)', idiom: '自動車', idiomMean: '원동기를 장치하여 움직이는 차', idiomEum: '자동차' },
        { hanja: '工', eum: '공', meaning: '장인', radical: '工(3획)', idiom: '工事多忙', idiomMean: '공적인 일과 사적인 일로 매우 바쁨', idiomEum: '공사다망' },
        { hanja: '空', eum: '공', meaning: '빌', radical: '穴(8획)', idiom: '空手來空手去', idiomMean: '빈손으로 와서 빈손으로 감', idiomEum: '공수래공수거' },
        { hanja: '記', eum: '기', meaning: '기록할', radical: '言(10획)', idiom: '記錄', idiomMean: '후일에 남길 목적으로 어떤 사실을 적음', idiomEum: '기록' },
        { hanja: '氣', eum: '기', meaning: '기운', radical: '气(10획)', idiom: '意氣揚揚', idiomMean: '뜻한 바를 이루어 만족하고 자랑스러운 모습', idiomEum: '의기양양' },
        { hanja: '男', eum: '남', meaning: '사내', radical: '田(7획)', antonym: '女(녀)', idiom: '男女老少', idiomMean: '남자와 여자, 늙은이와 젊은이 (모든 사람)', idiomEum: '남녀노소' },
        { hanja: '內', eum: '내', meaning: '안', radical: '入(4획)', antonym: '外(외)', idiom: '內憂外患', idiomMean: '나라 안의 걱정과 밖으로부터의 근심', idiomEum: '내우외환' },
        { hanja: '農', eum: '농', meaning: '농사', radical: '辰(13획)', idiom: '農者天下之大本', idiomMean: '농사는 천하의 사람들이 살아가는 큰 근본임', idiomEum: '농자천하지대본' },
        { hanja: '答', eum: '답', meaning: '대답할', radical: '竹(12획)', antonym: '問(문)', idiom: '東問西答', idiomMean: '동쪽을 묻는데 서쪽을 대답함 (엉뚱한 대답)', idiomEum: '동문서답' },
        { hanja: '道', eum: '도', meaning: '길', radical: '辵(13획)', idiom: '言語道斷', idiomMean: '말문이 막힘 (어이가 없어서 말도 안 나옴)', idiomEum: '언어도단' },
        { hanja: '動', eum: '동', meaning: '움직일', radical: '力(11획)', antonym: '靜(정)', idiom: '輕擧妄動', idiomMean: '가볍고 망령되게 행동함', idiomEum: '경거망동' },
        { hanja: '同', eum: '동', meaning: '같을', radical: '口(6획)', antonym: '異(이)', idiom: '同病相憐', idiomMean: '같은 병을 앓는 사람끼리 서로 가엾게 여김', idiomEum: '동병상련' },
        { hanja: '冬', eum: '동', meaning: '겨울', radical: '冫(5획)', antonym: '夏(하)', idiom: '春夏秋冬', idiomMean: '봄, 여름, 가을, 겨울 (사계절)', idiomEum: '춘하추동' },
        { hanja: '洞', eum: '동', meaning: '마을', radical: '水(9획)', idiom: '洞內', idiomMean: '마을의 안', idiomEum: '동내' },
        { hanja: '理', eum: '리', meaning: '다스릴', radical: '玉(11획)', idiom: '事必歸正', idiomMean: '모든 일은 반드시 바른길로 돌아감', idiomEum: '사필귀정' },
        { hanja: '林', eum: '림', meaning: '수풀', radical: '木(8획)', idiom: '森林', idiomMean: '나무가 빽빽하게 우거진 숲', idiomEum: '삼림' },
        { hanja: '面', eum: '면', meaning: '낯', radical: '面(9획)', idiom: '面從腹背', idiomMean: '앞에서는 복종하는 체하면서 속으로는 배반함', idiomEum: '면종복배' },
        { hanja: '命', eum: '명', meaning: '목숨', radical: '口(8획)', idiom: '絶體絶命', idiomMean: '몸도 목숨도 다 된 상태 (어찌할 수 없는 막다른 지경)', idiomEum: '절체절명' },
        { hanja: '文', eum: '문', meaning: '글', radical: '文(4획)', antonym: '武(무)', idiom: '文房四友', idiomMean: '서재에 꼭 있어야 할 네 가지 벗 (종이, 붓, 먹, 벼루)', idiomEum: '문방사우' },
        { hanja: '問', eum: '문', meaning: '물을', radical: '口(11획)', antonym: '答(답)', idiom: '自問自答', idiomMean: '스스로 묻고 스스로 대답함', idiomEum: '자문자답' },
        { hanja: '物', eum: '물', meaning: '만물', radical: '牛(8획)', idiom: '萬物相', idiomMean: '온갖 물건을 다 갖추어 놓고 파는 가게', idiomEum: '만물상' },
        { hanja: '方', eum: '방', meaning: '방향', radical: '方(4획)', idiom: '四面八方', idiomMean: '사방과 팔방 (모든 방향)', idiomEum: '사면팔방' },
        { hanja: '百', eum: '백', meaning: '일백', radical: '白(6획)', idiom: '百戰百勝', idiomMean: '백 번 싸워 백 번 이김', idiomEum: '백전백승' },
        { hanja: '夫', eum: '부', meaning: '지아비', radical: '大(4획)', antonym: '婦(부)', idiom: '夫婦有別', idiomMean: '남편과 아내 사이에는 분별이 있어야 함', idiomEum: '부부유별' },
        { hanja: '不', eum: '불', meaning: '아닐', radical: '一(4획)', idiom: '不知氣數', idiomMean: '그 수를 알지 못할 정도로 많음', idiomEum: '부지기수' },
        { hanja: '事', eum: '사', meaning: '일', radical: '亅(8획)', idiom: '萬事亨通', idiomMean: '모든 일이 뜻대로 잘 풀림', idiomEum: '만사형통' },
        { hanja: '算', eum: '산', meaning: '셈할', radical: '竹(14획)', idiom: '算數', idiomMean: '셈을 하는 방법이나 과목', idiomEum: '산수' },
        { hanja: '色', eum: '색', meaning: '빛', radical: '色(6획)', idiom: '五色玲瓏', idiomMean: '다섯 가지 빛깔이 찬란하고 아름다움', idiomEum: '오색영롱' },
        { hanja: '夕', eum: '석', meaning: '저녁', radical: '夕(3획)', antonym: '朝(조)', idiom: '朝三暮四', idiomMean: '간사한 꾀로 남을 속여 희롱함', idiomEum: '조삼모사' },
        { hanja: '星', eum: '성', meaning: '별', radical: '日(9획)', idiom: '流星', idiomMean: '하늘에서 떨어지는 별 (별똥별)', idiomEum: '유성' },
        { hanja: '所', eum: '소', meaning: '곳', radical: '戶(8획)', idiom: '適材適所', idiomMean: '알맞은 인재를 알맞은 자리에 씀', idiomEum: '적재적소' },
        { hanja: '數', eum: '수', meaning: '셈', radical: '攴(15획)', idiom: '數學', idiomMean: '수량이나 공간의 성질을 연구하는 학문', idiomEum: '수학' },
        { hanja: '語', eum: '어', meaning: '말씀', radical: '言(14획)', idiom: '千言萬語', idiomMean: '수많은 말 (매우 많은 말)', idiomEum: '천언만어' },
        { hanja: '夏', eum: '하', meaning: '여름', radical: '夊(10획)', antonym: '冬(동)', idiom: '立夏', idiomMean: '여름이 시작됨을 알리는 절기', idiomEum: '입하' },
        { hanja: '秋', eum: '추', meaning: '가을', radical: '禾(9획)', antonym: '春(춘)', idiom: '千秋萬代', idiomMean: '천 년 만 년의 오랜 세월', idiomEum: '천추만대' },
        { hanja: '春', eum: '춘', meaning: '봄', radical: '日(9획)', antonym: '秋(추)', idiom: '靑春', idiomMean: '새싹이 파랗게 돋아나는 봄철 (젊은 나이)', idiomEum: '청춘' },
        { hanja: '天', eum: '천', meaning: '하늘', radical: '大(4획)', antonym: '地(지)', idiom: '天高馬肥', idiomMean: '하늘은 높고 말은 살찐다 (가을이 좋은 계절임을 뜻함)', idiomEum: '천고마비' },
        { hanja: '千', eum: '천', meaning: '일천', radical: '十(3획)', idiom: '千載一遇', idiomMean: '천 년에 한 번 만날 수 있는 좋은 기회', idiomEum: '천재일우' },
        { hanja: '草', eum: '초', meaning: '풀', radical: '艸(10획)', idiom: '草綠同色', idiomMean: '풀색과 녹색은 같은 색 (같은 무리끼리 어울림)', idiomEum: '초록동색' },
        { hanja: '村', eum: '촌', meaning: '마을', radical: '木(7획)', idiom: '農村', idiomMean: '농사짓는 사람들이 모여 사는 마을', idiomEum: '농촌' },
        { hanja: '出', eum: '출', meaning: '나갈', radical: '凵(5획)', antonym: '入(입)', idiom: '神出鬼沒', idiomMean: '귀신처럼 나타났다 사라짐 (자유자재로 나타나고 숨음)', idiomEum: '신출귀몰' },
        { hanja: '入', eum: '입', meaning: '들어올', radical: '入(2획)', antonym: '出(출)', idiom: '入學', idiomMean: '학교에 들어감', idiomEum: '입학' },
        { hanja: '休', eum: '휴', meaning: '쉴', radical: '人(6획)', idiom: '休養林', idiomMean: '편안히 쉬면서 몸과 마음을 보양할 수 있는 숲', idiomEum: '휴양림' },
        { hanja: '花', eum: '화', meaning: '꽃', radical: '艸(8획)', idiom: '落花流水', idiomMean: '떨어지는 꽃과 흐르는 물 (가는 봄의 경치, 남녀가 서로 그리워함)', idiomEum: '낙화유수' },
        { hanja: '話', eum: '화', meaning: '말씀', radical: '言(13획)', idiom: '電話', idiomMean: '멀리 있는 사람과 음성을 주고받는 통신 기기', idiomEum: '전화' },
        { hanja: '地', eum: '지', meaning: '땅', radical: '土(6획)', antonym: '天(천)', idiom: '天地創造', idiomMean: '조물주가 세상의 만물을 처음으로 만듦', idiomEum: '천지창조' },
		{ hanja: '公', eum: '공', meaning: '공평할', radical: '八(4획)', idiom: '公平無私', idiomMean: '공평하여 사사로움이 없음', idiomEum: '공평무사' },
        { hanja: '共', eum: '공', meaning: '한가지', radical: '八(6획)', idiom: '同苦同樂', idiomMean: '괴로움도 즐거움도 함께함', idiomEum: '동고동락' },
        { hanja: '果', eum: '과', meaning: '열매', radical: '木(8획)', idiom: '因果應報', idiomMean: '원인과 결과가 서로 응하여 보답함', idiomEum: '인과응보' },
        { hanja: '科', eum: '과', meaning: '과목', radical: '禾(9획)', idiom: '科學', idiomMean: '보편적인 진리나 법칙을 발견하려는 학문', idiomEum: '과학' },
        { hanja: '區', eum: '구', meaning: '구분할', radical: '匸(11획)', idiom: '區分', idiomMean: '일정한 기준에 따라 갈라 나눔', idiomEum: '구분' },
        { hanja: '球', eum: '구', meaning: '공', radical: '玉(11획)', idiom: '地球', idiomMean: '우리가 살고 있는 천체', idiomEum: '지구' },
        { hanja: '郡', eum: '군', meaning: '고을', radical: '邑(10획)', idiom: '郡守', idiomMean: '한 군(郡)의 행정을 맡아보는 우두머리', idiomEum: '군수' },
        { hanja: '近', eum: '근', meaning: '가까울', radical: '辵(7획)', antonym: '遠(원)', idiom: '近墨者黑', idiomMean: '먹을 가까이하는 사람은 검어짐', idiomEum: '근묵자흑' },
        { hanja: '根', eum: '근', meaning: '뿌리', radical: '木(10획)', idiom: '根本', idiomMean: '사물이 생겨나는 본바탕', idiomEum: '근본' },
        { hanja: '己', eum: '기', meaning: '몸', radical: '己(3획)', idiom: '克己復禮', idiomMean: '자신의 욕망을 이기고 예의를 회복함', idiomEum: '극기복례' },
        { hanja: '旗', eum: '기', meaning: '기', radical: '方(14획)', idiom: '國旗', idiomMean: '한 나라를 상징하는 기', idiomEum: '국기' },
        { hanja: '起', eum: '기', meaning: '일어날', radical: '走(10획)', idiom: '起死回生', idiomMean: '죽을 고비에서 벗어나 다시 살아남', idiomEum: '기사회생' },
        { hanja: '多', eum: '다', meaning: '많을', radical: '夕(6획)', antonym: '少(소)', idiom: '多多益善', idiomMean: '많으면 많을수록 더욱 좋음', idiomEum: '다다익선' },
        { hanja: '短', eum: '단', meaning: '짧을', radical: '矢(12획)', antonym: '長(장)', idiom: '一長一短', idiomMean: '장점도 있고 단점도 있음', idiomEum: '일장일단' },
        { hanja: '代', eum: '대', meaning: '대신할', radical: '人(5획)', idiom: '代代孫孫', idiomMean: '대대로 이어지는 자손', idiomEum: '대대손손' },
        { hanja: '對', eum: '대', meaning: '대할', radical: '寸(14획)', idiom: '對面', idiomMean: '서로 얼굴을 마주 봄', idiomEum: '대면' },
        { hanja: '圖', eum: '도', meaning: '그림', radical: '囗(14획)', idiom: '圖書館', idiomMean: '온갖 책을 모아 두고 읽게 하는 시설', idiomEum: '도서관' },
        { hanja: '度', eum: '도', meaning: '법도', radical: '广(9획)', idiom: '態度', idiomMean: '어떤 일이나 상황을 대하는 마음가짐', idiomEum: '태도' },
        { hanja: '童', eum: '동', meaning: '아이', radical: '立(12획)', idiom: '童心', idiomMean: '어린아이의 마음', idiomEum: '동심' },
        { hanja: '頭', eum: '두', meaning: '머리', radical: '頁(16획)', idiom: '頭角', idiomMean: '머리 위의 뿔 (뛰어난 재능을 드러냄)', idiomEum: '두각' },
        { hanja: '等', eum: '등', meaning: '무리', radical: '竹(12획)', idiom: '平等', idiomMean: '차별 없이 고르고 한결같음', idiomEum: '평등' },
        { hanja: '樂', eum: '락', meaning: '즐거울', radical: '木(15획)', antonym: '苦(고)', idiom: '苦盡甘來', idiomMean: '고생이 다하면 즐거움이 옴', idiomEum: '고진감래' }, // 참고: 악(음악), 락(즐거울), 요(좋아할) 3가지 음이 있음
        { hanja: '老', eum: '로', meaning: '늙을', radical: '老(6획)', antonym: '少(소)', idiom: '男女老少', idiomMean: '남녀와 노인, 아이 (모든 사람)', idiomEum: '남녀노소' },
        { hanja: '里', eum: '리', meaning: '마을', radical: '里(7획)', idiom: '千里眼', idiomMean: '천 리 밖을 보는 눈 (먼 곳의 일을 아는 능력)', idiomEum: '천리안' },
        { hanja: '立', eum: '립', meaning: '설', radical: '立(5획)', idiom: '自立', idiomMean: '남에게 의지하지 않고 스스로 섬', idiomEum: '자립' },
        { hanja: '買', eum: '매', meaning: '살', radical: '貝(12획)', antonym: '賣(매)', idiom: '買賣', idiomMean: '물건을 사고팖', idiomEum: '매매' },
        { hanja: '賣', eum: '매', meaning: '팔', radical: '貝(15획)', antonym: '買(매)', idiom: '賣國奴', idiomMean: '나라를 팔아먹은 배신자', idiomEum: '매국노' },
        { hanja: '麥', eum: '맥', meaning: '보리', radical: '麥(11획)', idiom: '麥秋', idiomMean: '보리를 거두어들이는 때 (초여름)', idiomEum: '맥추' },
        { hanja: '明', eum: '명', meaning: '밝을', radical: '日(8획)', antonym: '暗(암)', idiom: '明若觀火', idiomMean: '불을 보듯 뻔하고 명백함', idiomEum: '명약관화' },
        { hanja: '目', eum: '목', meaning: '눈', radical: '目(5획)', idiom: '刮目相對', idiomMean: '눈을 비비고 다시 봄 (학식이나 재주가 놀랍게 발전함)', idiomEum: '괄목상대' },
        { hanja: '半', eum: '반', meaning: '반', radical: '十(5획)', idiom: '半信半疑', idiomMean: '반은 믿고 반은 의심함', idiomEum: '반신반의' },
        { hanja: '番', eum: '번', meaning: '차례', radical: '田(12획)', idiom: '番號', idiomMean: '차례를 매긴 숫자', idiomEum: '번호' },
        { hanja: '本', eum: '본', meaning: '근본', radical: '木(5획)', antonym: '末(말)', idiom: '本末顚倒', idiomMean: '근본과 끝이 뒤바뀜 (일의 순서가 뒤바뀜)', idiomEum: '본말전도' },
        { hanja: '部', eum: '부', meaning: '떼', radical: '邑(11획)', idiom: '部分', idiomMean: '전체의 갈라진 일부분', idiomEum: '부분' },
        { hanja: '分', eum: '분', meaning: '나눌', radical: '八(4획)', idiom: '四分五裂', idiomMean: '넷으로 나뉘고 다섯으로 찢어짐', idiomEum: '사분오열' },
        { hanja: '死', eum: '사', meaning: '죽을', radical: '歹(6획)', antonym: '生(생)', idiom: '九死一生', idiomMean: '아홉 번 죽을 고비에서 겨우 살아남', idiomEum: '구사일생' },
        { hanja: '線', eum: '선', meaning: '줄', radical: '糸(15획)', idiom: '直線', idiomMean: '곧게 뻗은 줄이나 선', idiomEum: '직선' },
        { hanja: '雪', eum: '설', meaning: '눈', radical: '雨(11획)', idiom: '雪上加霜', idiomMean: '눈 위에 서리가 내림 (어려운 일이 겹침)', idiomEum: '설상가상' },
        { hanja: '少', eum: '소', meaning: '적을', radical: '小(4획)', antonym: '多(다)', idiom: '少數', idiomMean: '적은 수', idiomEum: '소수' },
        { hanja: '食', eum: '식', meaning: '밥/먹을', radical: '食(9획)', idiom: '食口', idiomMean: '한집에서 함께 살면서 끼니를 같이하는 사람', idiomEum: '식구' },
        { hanja: '新', eum: '신', meaning: '새', radical: '斤(13획)', antonym: '舊(구)', idiom: '溫故知新', idiomMean: '옛것을 익히고 그것을 미루어 새것을 앎', idiomEum: '온고지신' },
        { hanja: '心', eum: '심', meaning: '마음', radical: '心(4획)', idiom: '以心傳心', idiomMean: '마음과 마음으로 서로 뜻이 통함', idiomEum: '이심전심' },
        { hanja: '安', eum: '안', meaning: '편안할', radical: '宀(6획)', antonym: '危(위)', idiom: '平安', idiomMean: '근심이나 걱정이 없이 편안함', idiomEum: '평안' },
        { hanja: '夜', eum: '야', meaning: '밤', radical: '夕(8획)', antonym: '晝(주)', idiom: '晝夜', idiomMean: '낮과 밤', idiomEum: '주야' },
        { hanja: '野', eum: '야', meaning: '들', radical: '里(11획)', idiom: '野心', idiomMean: '무엇을 이루어 보려는 제 분수에 넘치는 큰 마음', idiomEum: '야심' },
        { hanja: '弱', eum: '약', meaning: '약할', radical: '弓(10획)', antonym: '强(강)', idiom: '弱肉强食', idiomMean: '약한 자의 고기를 강한 자가 먹음', idiomEum: '약육강식' },
        { hanja: '藥', eum: '약', meaning: '약', radical: '艸(19획)', idiom: '良藥苦口', idiomMean: '좋은 약은 입에 씀', idiomEum: '양약고구' },
        { hanja: '洋', eum: '양', meaning: '큰바다', radical: '水(9획)', idiom: '大洋', idiomMean: '아주 크고 넓은 바다', idiomEum: '대양' },
        { hanja: '言', eum: '언', meaning: '말씀', radical: '言(7획)', idiom: '流言蜚語', idiomMean: '근거 없이 널리 퍼진 소문', idiomEum: '유언비어' },
        { hanja: '然', eum: '연', meaning: '그러할', radical: '火(12획)', idiom: '自然', idiomMean: '사람의 힘을 더하지 않은 있는 그대로의 상태', idiomEum: '자연' }
    ],
    'level6': [
        { hanja: '各', eum: '각', meaning: '각각', radical: '夂(6획)', idiom: '各自圖生', idiomMean: '각자가 스스로 살아갈 방법을 도모함', idiomEum: '각자도생' },
        { hanja: '角', eum: '각', meaning: '뿔/모퉁이', radical: '角(7획)', idiom: '角逐', idiomMean: '서로 이기려고 다툼', idiomEum: '각축' },
        { hanja: '感', eum: '감', meaning: '느낄', radical: '心(13획)', idiom: '感謝', idiomMean: '고마움을 느껴 감사히 여김', idiomEum: '감사' },
        { hanja: '强', eum: '강', meaning: '강할', radical: '弓(12획)', antonym: '弱(약)', idiom: '自强不息', idiomMean: '스스로 힘써 쉬지 않고 노력함', idiomEum: '자강불식' },
        { hanja: '客', eum: '객', meaning: '손님', radical: '宀(9획)', antonym: '主(주)', idiom: '客地', idiomMean: '고향을 떠나 타향에서 삶', idiomEum: '객지' },
        { hanja: '見', eum: '견', meaning: '볼', radical: '見(7획)', synonym: '視(시)', idiom: '見物生心', idiomMean: '물건을 보면 욕심이 생김', idiomEum: '견물생심' },
        { hanja: '決', eum: '결', meaning: '결정할', radical: '水(7획)', idiom: '決斷', idiomMean: '결단력 있게 판단하여 단정함', idiomEum: '결단' },
        { hanja: '結', eum: '결', meaning: '맺을', radical: '糸(12획)', antonym: '解(해)', idiom: '結草報恩', idiomMean: '풀을 엮어 은혜를 갚음', idiomEum: '결초보은' },
        { hanja: '計', eum: '계', meaning: '셀/꾀', radical: '言(9획)', idiom: '計劃', idiomMean: '앞으로 할 일의 절차나 방법을 미리 세운 내용', idiomEum: '계획' },
        { hanja: '古', eum: '고', meaning: '옛', radical: '口(5획)', antonym: '今(금)', idiom: '古今東西', idiomMean: '예와 지금, 동양과 서양을 통틀어 이름', idiomEum: '고금동서' },
        { hanja: '共', eum: '공', meaning: '함께', radical: '八(6획)', idiom: '共同', idiomMean: '둘 이상이 함께 일을 하거나 같이 가짐', idiomEum: '공동' },
        { hanja: '課', eum: '과', meaning: '과목', radical: '言(15획)', idiom: '課題', idiomMean: '해결하거나 해내야 할 문제나 임무', idiomEum: '과제' },
        { hanja: '關', eum: '관', meaning: '관계할', radical: '門(19획)', idiom: '關心', idiomMean: '어떤 것에 마음이 끌려 주의를 기울임', idiomEum: '관심' },
        { hanja: '光', eum: '광', meaning: '빛', radical: '儿(6획)', idiom: '光明', idiomMean: '밝고 환한 빛, 또는 밝은 미래', idiomEum: '광명' },
        { hanja: '球', eum: '구', meaning: '공', radical: '玉(11획)', idiom: '地球', idiomMean: '인류가 살고 있는 행성', idiomEum: '지구' },
        { hanja: '近', eum: '근', meaning: '가까울', radical: '辵(8획)', antonym: '遠(원)', idiom: '近墨者黑', idiomMean: '먹 가까이 있으면 검어짐, 환경의 중요성', idiomEum: '근묵자흑' },
        { hanja: '記', eum: '기', meaning: '기록할', radical: '言(10획)', idiom: '記憶', idiomMean: '이전의 경험이나 인상을 의식 속에 간직하거나 떠올림', idiomEum: '기억' },
        { hanja: '基', eum: '기', meaning: '터/기초', radical: '土(11획)', idiom: '基礎', idiomMean: '사물의 가장 기본이 되는 토대', idiomEum: '기초' },
        { hanja: '農', eum: '농', meaning: '농사', radical: '辰(13획)', idiom: '農夫', idiomMean: '농사를 짓는 사람', idiomEum: '농부' },
        { hanja: '同', eum: '동', meaning: '같을', radical: '口(6획)', antonym: '異(이)', idiom: '同苦同樂', idiomMean: '고생도 즐거움도 함께함', idiomEum: '동고동락' },
        { hanja: '動', eum: '동', meaning: '움직일', radical: '力(11획)', antonym: '靜(정)', idiom: '動靜', idiomMean: '움직임과 정지, 또는 그 상황', idiomEum: '동정' },
        { hanja: '力', eum: '력', meaning: '힘', radical: '力(2획)', idiom: '努力', idiomMean: '목적을 이루기 위해 몸과 마음을 다하여 애씀', idiomEum: '노력' },
        { hanja: '立', eum: '립', meaning: '설', radical: '立(5획)', antonym: '臥(와)', idiom: '自立', idiomMean: '남에게 의지하지 않고 스스로 섬', idiomEum: '자립' },
        { hanja: '面', eum: '면', meaning: '낯/면', radical: '面(9획)', idiom: '面目', idiomMean: '남을 대할 만한 체면이나 명예', idiomEum: '면목' },
        { hanja: '命', eum: '명', meaning: '목숨/명령', radical: '口(8획)', idiom: '命在頃刻', idiomMean: '생명이 경각에 달려 있음', idiomEum: '명재경각' },
        { hanja: '問', eum: '문', meaning: '물을', radical: '口(11획)', antonym: '答(답)', idiom: '問答', idiomMean: '묻고 대답함', idiomEum: '문답' },
        { hanja: '反', eum: '반', meaning: '돌이킬', radical: '又(4획)', idiom: '反面敎師', idiomMean: '부정적인 면에서 가르침을 주는 스승', idiomEum: '반면교사' },
        { hanja: '半', eum: '반', meaning: '반/절반', radical: '十(5획)', idiom: '折半', idiomMean: '반으로 나눔', idiomEum: '절반' },
        { hanja: '放', eum: '방', meaning: '놓을', radical: '攴(8획)', idiom: '放心', idiomMean: '마음을 놓아 버려 조심하지 않음', idiomEum: '방심' },
        { hanja: '法', eum: '법', meaning: '법', radical: '水(8획)', idiom: '法道', idiomMean: '법과 도리', idiomEum: '법도' },
        { hanja: '別', eum: '별', meaning: '나눌/다를', radical: '刀(7획)', antonym: '合(합)', idiom: '別有天地', idiomMean: '딴 세상이 따로 있음, 경치가 매우 아름다운 곳', idiomEum: '별유천지' },
        { hanja: '服', eum: '복', meaning: '옷/복종', radical: '月(8획)', idiom: '服從', idiomMean: '남의 명령이나 의사에 따름', idiomEum: '복종' },
        { hanja: '福', eum: '복', meaning: '복', radical: '示(14획)', antonym: '禍(화)', idiom: '五福', idiomMean: '수·부·강녕·유호덕·고종명의 다섯 가지 복', idiomEum: '오복' },
        { hanja: '使', eum: '사', meaning: '부릴/사신', radical: '人(8획)', idiom: '使命', idiomMean: '맡겨진 임무', idiomEum: '사명' },
        { hanja: '事', eum: '사', meaning: '일', radical: '亅(8획)', idiom: '事必歸正', idiomMean: '모든 일은 반드시 올바른 데로 돌아감', idiomEum: '사필귀정' },
        { hanja: '産', eum: '산', meaning: '낳을/생산', radical: '生(11획)', idiom: '生産', idiomMean: '인간이 생활에 필요한 것을 만들어 냄', idiomEum: '생산' },
        { hanja: '算', eum: '산', meaning: '셈', radical: '竹(14획)', idiom: '算數', idiomMean: '수를 세거나 계산하는 것', idiomEum: '산수' },
        { hanja: '色', eum: '색', meaning: '빛/색깔', radical: '色(6획)', idiom: '五色', idiomMean: '청·적·황·백·흑의 다섯 가지 색', idiomEum: '오색' },
        { hanja: '成', eum: '성', meaning: '이룰', radical: '戈(7획)', antonym: '敗(패)', idiom: '成功', idiomMean: '원하는 바를 이룸', idiomEum: '성공' },
        { hanja: '速', eum: '속', meaning: '빠를', radical: '辵(11획)', antonym: '遲(지)', idiom: '速戰速決', idiomMean: '빨리 싸워 빨리 결판을 냄', idiomEum: '속전속결' },
        { hanja: '身', eum: '신', meaning: '몸', radical: '身(7획)', idiom: '身言書判', idiomMean: '인물을 평가하는 체모·언변·문필·판단력 네 기준', idiomEum: '신언서판' },
        { hanja: '失', eum: '실', meaning: '잃을', radical: '大(5획)', antonym: '得(득)', idiom: '失敗', idiomMean: '일을 잘못하여 그르침', idiomEum: '실패' },
        { hanja: '用', eum: '용', meaning: '쓸', radical: '用(5획)', idiom: '用意周到', idiomMean: '준비가 두루 잘 갖추어져 있음', idiomEum: '용의주도' },
        { hanja: '原', eum: '원', meaning: '근원', radical: '厂(10획)', idiom: '原因', idiomMean: '어떤 일이 일어난 근본 이유', idiomEum: '원인' },
        { hanja: '由', eum: '유', meaning: '말미암을', radical: '田(5획)', idiom: '自由', idiomMean: '자기 마음대로 행동할 수 있는 상태', idiomEum: '자유' },
        { hanja: '意', eum: '의', meaning: '뜻', radical: '心(13획)', idiom: '意志', idiomMean: '어떤 일을 이루고자 하는 마음', idiomEum: '의지' },
        { hanja: '育', eum: '육', meaning: '기를', radical: '肉(8획)', idiom: '敎育', idiomMean: '지식과 기술 등을 가르치며 인격을 기름', idiomEum: '교육' },
        { hanja: '音', eum: '음', meaning: '소리', radical: '音(9획)', synonym: '聲(성)', idiom: '音信不通', idiomMean: '소식이나 연락이 전혀 없음', idiomEum: '음신불통' },
        { hanja: '情', eum: '정', meaning: '뜻/감정', radical: '心(11획)', idiom: '情報', idiomMean: '어떤 상황이나 사정에 관한 소식이나 자료', idiomEum: '정보' },
        { hanja: '競', eum: '경', meaning: '다툴', radical: '立(20획)', idiom: '競爭', idiomMean: '같은 목적에 대하여 이기거나 앞서려고 서로 겨룸', idiomEum: '경쟁' }
    ]
};
